/**
 * Globe genre strings → the genre graph.
 *
 * The globe's events carry ~760 distinct free-text genre strings. This table
 * lands each on a GENRE (when the string simply is that genre) or on a
 * SUBGENRE with a parent, so 'Art Rock' and 'Rock' meet without 'Art Rock'
 * being lost.
 *
 * Three things are deliberately NOT genres here:
 *  - INSTRUMENT_TAGS — Marimba, Mbira, Oud Music. The graph has an `instrument`
 *    node kind, and an instrument link says more than a genre guess would.
 *  - IGNORED_GENRE_TAGS — 'World Music', 'Festival', 'Compilation'. They
 *    describe reach or format. Every event using one also carries a real tag.
 *  - UNPLACED_GENRE_TAGS — 129 traditions nobody has placed yet, listed rather
 *    than bucketed. They resolve to null: the Atlas says it does not know.
 */

import { getGenre } from './genres';

/** A globe genre string resolved into the graph. */
export interface ResolvedGenre {
  genre: string;
  subgenre?: string;
}

/** Subgenre id → parent genre id. */
export const SUBGENRE_PARENT: Record<string, string> = {
  // ── Rock ──
  'aboriginal-rock': 'rock',
  'acid-rock': 'rock',
  alternative: 'rock',
  'alternative-metal': 'rock',
  'alternative-rock': 'rock',
  'anatolian-rock': 'rock',
  'arabic-indie': 'rock',
  'arabic-indie-rock': 'rock',
  'art-punk': 'rock',
  'art-rock': 'rock',
  'black-metal': 'rock',
  britpop: 'rock',
  'cambodian-rock': 'rock',
  'classic-pop-rock': 'rock',
  'classic-rock': 'rock',
  'classic-rock-pop': 'rock',
  'death-metal': 'rock',
  'desert-rock': 'rock',
  emo: 'rock',
  experimental: 'rock',
  'extreme-metal': 'rock',
  'filipino-rock': 'rock',
  'garage-rock': 'rock',
  'garage-rock-revival': 'rock',
  'glam-pop': 'rock',
  'glam-rock': 'rock',
  'groove-metal': 'rock',
  'group-sounds': 'rock',
  grunge: 'rock',
  'grunge-rock': 'rock',
  'hard-rock': 'rock',
  hardcore: 'rock',
  'hardcore-punk': 'rock',
  'heartland-rock': 'rock',
  'heavy-metal': 'rock',
  indie: 'rock',
  'indie-dance': 'rock',
  'indie-pop': 'rock',
  'indie-rock': 'rock',
  'jam-rock': 'rock',
  'japanese-rock': 'rock',
  krautrock: 'rock',
  'lounge-rock': 'rock',
  'malay-rock': 'rock',
  'math-rock': 'rock',
  merseybeat: 'rock',
  metal: 'rock',
  metalcore: 'rock',
  'neo-psychedelia': 'rock',
  'new-wave': 'rock',
  noise: 'rock',
  'noise-pop': 'rock',
  'noise-rock': 'rock',
  'nu-metal': 'rock',
  'political-rock': 'rock',
  'pop-punk': 'rock',
  'pop-rock': 'rock',
  'post-grunge': 'rock',
  'post-hardcore': 'rock',
  'post-punk': 'rock',
  'post-punk-revival': 'rock',
  'post-rock': 'rock',
  'post-soviet-rock': 'rock',
  'progressive-metal': 'rock',
  'progressive-rock': 'rock',
  'proto-punk': 'rock',
  psychedelic: 'rock',
  'psychedelic-rock': 'rock',
  'pub-rock': 'rock',
  punk: 'rock',
  'punk-rock': 'rock',
  'punta-rock': 'rock',
  'raga-rock': 'rock',
  'riot-grrrl': 'rock',
  'rock-and-roll': 'rock',
  'rock-en-espa-u00f1ol': 'rock',
  'rock-en-espanol': 'rock',
  'rock-pop': 'rock',
  'rock-roll': 'rock',
  'rock-shuffle': 'rock',
  rockabilly: 'rock',
  'sad-girl-indie': 'rock',
  screamo: 'rock',
  'shock-rock': 'rock',
  shoegaze: 'rock',
  'shuffle-rock': 'rock',
  'soft-rock': 'rock',
  'southern-rock': 'rock',
  'straight-eighth-classic-rock': 'rock',
  'straight-eighth-pop-rock': 'rock',
  'straight-eighth-rock': 'rock',
  'thrash-metal': 'rock',
  'uk-garage': 'rock',
  zamrock: 'rock',
  // ── Pop ──
  'adult-contemporary': 'pop',
  'afro-pop': 'pop',
  'arabian-pop': 'pop',
  'arabic-pop': 'pop',
  'art-pop': 'pop',
  ballad: 'pop',
  'bubblegum-pop': 'pop',
  'c-pop': 'pop',
  'city-pop': 'pop',
  'classic-pop': 'pop',
  dance: 'pop',
  'dance-music': 'pop',
  'dance-pop': 'pop',
  'dark-pop': 'pop',
  'easy-listening': 'pop',
  europop: 'pop',
  'gulf-pop': 'pop',
  hyperpop: 'pop',
  'indonesian-pop': 'pop',
  'j-pop': 'pop',
  'jangle-pop': 'pop',
  jingles: 'pop',
  'k-pop': 'pop',
  'kenyan-pop': 'pop',
  'khaleeji-pop': 'pop',
  'khmer-pop': 'pop',
  'malaysian-pop': 'pop',
  'mande-pop': 'pop',
  mandopop: 'pop',
  'mediterranean-pop': 'pop',
  'musical-theatre': 'pop',
  'north-korean-pop': 'pop',
  'persian-pop': 'pop',
  'polynesian-pop': 'pop',
  'pop-ballad': 'pop',
  'pop-ballad-slow-rubato': 'pop',
  'pop-waltz': 'pop',
  'power-ballad': 'pop',
  'power-pop': 'pop',
  'sri-lankan-pop': 'pop',
  standards: 'pop',
  'stick-dance': 'pop',
  'straight-eighth-pop': 'pop',
  'teen-pop': 'pop',
  'township-pop': 'pop',
  'turkish-pop': 'pop',
  'uk-dance': 'pop',
  vaudeville: 'pop',
  'zulu-pop': 'pop',
  // ── Funk ──
  'acoustic-soul': 'funk',
  'afro-funk': 'funk',
  'afro-soul': 'funk',
  'alternative-r-b': 'funk',
  'baile-funk': 'funk',
  'blue-eyed-soul': 'funk',
  'classic-motown': 'funk',
  'classic-r-b': 'funk',
  'classic-soul': 'funk',
  disco: 'funk',
  'electro-funk': 'funk',
  'folk-soul': 'funk',
  'funk-pop': 'funk',
  'funk-rock': 'funk',
  funky: 'funk',
  'funky-motown': 'funk',
  'funky-pop': 'funk',
  'funky-soul': 'funk',
  'future-soul': 'funk',
  'go-go': 'funk',
  gospel: 'funk',
  'gospel-choir': 'funk',
  motown: 'funk',
  'neo-soul': 'funk',
  'new-orleans-funk': 'funk',
  'new-orleans-r-b': 'funk',
  'p-funk': 'funk',
  'philadelphia-soul': 'funk',
  'psychedelic-funk': 'funk',
  'psychedelic-soul': 'funk',
  'punk-funk': 'funk',
  'r-and-b': 'funk',
  soul: 'funk',
  'soul-r-b': 'funk',
  'southern-soul': 'funk',
  'straight-eighth-funk': 'funk',
  'straight-eighth-funky-soul': 'funk',
  'thai-funk': 'funk',
  'tribal-funk': 'funk',
  wassoulou: 'funk',
  // ── Folk ──
  acoustic: 'folk',
  'acoustic-rock': 'folk',
  'afar-folk': 'folk',
  'alt-country': 'folk',
  americana: 'folk',
  'andean-folk': 'folk',
  appalachian: 'folk',
  'armenian-folk': 'folk',
  'bengali-folk': 'folk',
  'bhutanese-folk': 'folk',
  bluegrass: 'folk',
  celtic: 'folk',
  'classic-country': 'folk',
  'classic-folk-rock': 'folk',
  country: 'folk',
  'country-ballad': 'folk',
  'country-folk': 'folk',
  'country-pop': 'folk',
  'country-pop-ballad': 'folk',
  'country-rock': 'folk',
  'fijian-folk': 'folk',
  'folk-ballad': 'folk',
  'folk-pop': 'folk',
  'folk-punk': 'folk',
  'folk-rock': 'folk',
  'folk-song': 'folk',
  'greek-folk': 'folk',
  'indie-folk': 'folk',
  'indie-folk-rock': 'folk',
  'irish-folk': 'folk',
  'kazakh-folk': 'folk',
  'kyrgyz-folk': 'folk',
  'lebanese-folk': 'folk',
  'maldivian-folk': 'folk',
  'mongolian-folk': 'folk',
  'nauruan-folk': 'folk',
  'nepali-folk': 'folk',
  'newari-folk': 'folk',
  'old-time': 'folk',
  'omani-folk': 'folk',
  'outlaw-country': 'folk',
  'pacific-folk': 'folk',
  'pashto-folk': 'folk',
  protest: 'folk',
  'protest-folk': 'folk',
  'protest-music': 'folk',
  'rodeo-country': 'folk',
  'scandinavian-folk': 'folk',
  'sesotho-traditional': 'folk',
  'singer-songwriter': 'folk',
  'string-band': 'folk',
  'sudanese-folk': 'folk',
  'swazi-traditional': 'folk',
  traditional: 'folk',
  'traditional-ballad': 'folk',
  'turbo-folk': 'folk',
  'turkish-folk': 'folk',
  'turkmen-folk': 'folk',
  'vietnamese-folk': 'folk',
  western: 'folk',
  'yemeni-folk': 'folk',
  // ── Jazz ──
  'afro-fusion': 'jazz',
  'afro-jazz': 'jazz',
  afroswing: 'jazz',
  'avant-garde': 'jazz',
  'avant-garde-jazz': 'jazz',
  'azerbaijani-jazz': 'jazz',
  bebop: 'jazz',
  'big-band': 'jazz',
  'blues-jazz': 'jazz',
  'cape-jazz': 'jazz',
  'classic-jazz-pop': 'jazz',
  'contemporary-jazz': 'jazz',
  'cool-jazz': 'jazz',
  dixieland: 'jazz',
  'ecm-jazz': 'jazz',
  'ethio-jazz': 'jazz',
  'free-jazz': 'jazz',
  'funk-fusion': 'jazz',
  'funky-jazz': 'jazz',
  'funky-jazz-soul': 'jazz',
  'funky-soul-jazz': 'jazz',
  'hard-bop': 'jazz',
  'hot-jazz': 'jazz',
  'jazz-ballad': 'jazz',
  'jazz-funk': 'jazz',
  'jazz-fusion': 'jazz',
  'jazz-waltz': 'jazz',
  'jazzy-pop': 'jazz',
  'modal-jazz': 'jazz',
  'neo-bop': 'jazz',
  'new-jack-swing': 'jazz',
  'post-bop': 'jazz',
  ragtime: 'jazz',
  'slow-swing': 'jazz',
  'somali-jazz': 'jazz',
  'soul-jazz': 'jazz',
  'spanish-african-fusion': 'jazz',
  'spiritual-jazz': 'jazz',
  swing: 'jazz',
  'township-jazz': 'jazz',
  'vocal-jazz': 'jazz',
  'west-coast-jazz': 'jazz',
  // ── Hip Hop ──
  'abstract-hip-hop': 'hip-hop',
  'african-hip-hop': 'hip-hop',
  'alternative-hip-hop': 'hip-hop',
  'brazilian-hip-hop': 'hip-hop',
  'conscious-rap': 'hip-hop',
  crunk: 'hip-hop',
  'cuban-hip-hop': 'hip-hop',
  drill: 'hip-hop',
  'east-coast-rap': 'hip-hop',
  'experimental-hip-hop': 'hip-hop',
  'g-funk': 'hip-hop',
  'gospel-rap': 'hip-hop',
  grime: 'hip-hop',
  'gully-rap': 'hip-hop',
  'hardcore-rap': 'hip-hop',
  'hip-hop-r-b': 'hip-hop',
  'hip-hop-soul': 'hip-hop',
  'indian-hip-hop': 'hip-hop',
  'indie-hip-hop': 'hip-hop',
  'japanese-hip-hop': 'hip-hop',
  'jazz-rap': 'hip-hop',
  'k-hip-hop': 'hip-hop',
  'latin-hip-hop': 'hip-hop',
  'latin-trap': 'hip-hop',
  'political-rap': 'hip-hop',
  'pop-rap': 'hip-hop',
  'psychedelic-rap': 'hip-hop',
  rap: 'hip-hop',
  'rap-metal': 'hip-hop',
  'rap-rock': 'hip-hop',
  'southern-hip-hop': 'hip-hop',
  trap: 'hip-hop',
  'uk-drill': 'hip-hop',
  'uk-hip-hop': 'hip-hop',
  'underground-hip-hop': 'hip-hop',
  'west-coast-hip-hop': 'hip-hop',
  // ── Reggae ──
  'alternative-reggae': 'reggae',
  'california-reggae': 'reggae',
  dancehall: 'reggae',
  dembow: 'reggae',
  dub: 'reggae',
  dubstep: 'reggae',
  'european-reggae': 'reggae',
  'funky-reggae': 'reggae',
  'island-reggae': 'reggae',
  'lovers-rock': 'reggae',
  maskandi: 'reggae',
  mento: 'reggae',
  'pacific-reggae': 'reggae',
  'post-dubstep': 'reggae',
  ragga: 'reggae',
  'ragga-soca': 'reggae',
  'reggae-en-espa-u00f1ol': 'reggae',
  'reggae-fusion': 'reggae',
  'reggae-pop': 'reggae',
  'reggae-revival': 'reggae',
  reggaeton: 'reggae',
  rocksteady: 'reggae',
  'roots-reggae': 'reggae',
  'samba-reggae': 'reggae',
  ska: 'reggae',
  'ska-punk': 'reggae',
  'ska-revival': 'reggae',
  'ska-rock': 'reggae',
  // ── Latin ──
  'afro-cuban': 'latin',
  'afro-cuban-jazz': 'latin',
  bachata: 'latin',
  bolero: 'latin',
  'bossa-nova': 'latin',
  'cha-cha-cha': 'latin',
  charanga: 'latin',
  chicha: 'latin',
  cumbia: 'latin',
  'cumbia-peruana': 'latin',
  'cumbia-rock': 'latin',
  'cumbia-sonidera': 'latin',
  'cumbia-villera': 'latin',
  danzon: 'latin',
  'electro-cumbia': 'latin',
  flamenco: 'latin',
  'latin-alternative': 'latin',
  'latin-boogaloo': 'latin',
  'latin-folk': 'latin',
  'latin-funk': 'latin',
  'latin-jazz': 'latin',
  'latin-pop': 'latin',
  'latin-rock': 'latin',
  'latin-urban': 'latin',
  mambo: 'latin',
  merengue: 'latin',
  mpb: 'latin',
  norteno: 'latin',
  'nueva-canci-u00f3n': 'latin',
  'nueva-cancion': 'latin',
  'nuevo-tango': 'latin',
  ranchera: 'latin',
  'rock-latino': 'latin',
  salsa: 'latin',
  samba: 'latin',
  'samba-de-roda': 'latin',
  'samba-rock': 'latin',
  'son-cubano': 'latin',
  tango: 'latin',
  timba: 'latin',
  tropicalia: 'latin',
  // ── Blues ──
  'acoustic-blues': 'blues',
  'blues-rock': 'blues',
  'bluesy-pop': 'blues',
  boogie: 'blues',
  'british-blues': 'blues',
  'chicago-blues': 'blues',
  'classic-blues': 'blues',
  'country-blues': 'blues',
  'delta-blues': 'blues',
  'desert-blues': 'blues',
  'electric-blues': 'blues',
  'folk-blues': 'blues',
  'hill-country-blues': 'blues',
  'memphis-blues': 'blues',
  'piedmont-blues': 'blues',
  'punk-blues': 'blues',
  'soul-blues': 'blues',
  'talking-blues': 'blues',
  'texas-blues': 'blues',
  'tuareg-blues': 'blues',
  'world-blues': 'blues',
  // ── Electronic ──
  'acid-house': 'electronic',
  amapiano: 'electronic',
  ambient: 'electronic',
  'ambient-techno': 'electronic',
  'balearic-beat': 'electronic',
  downtempo: 'electronic',
  'drum-and-bass': 'electronic',
  edm: 'electronic',
  'electronic-rock': 'electronic',
  electronica: 'electronic',
  electropop: 'electronic',
  house: 'electronic',
  idm: 'electronic',
  industrial: 'electronic',
  jungle: 'electronic',
  kuduro: 'electronic',
  'minimal-techno': 'electronic',
  psytrance: 'electronic',
  'synth-pop': 'electronic',
  techno: 'electronic',
  technopop: 'electronic',
  trance: 'electronic',
  // ── Classical ──
  'afghan-classical': 'classical',
  'andalusi-classical': 'classical',
  'andalusian-classical': 'classical',
  'arabic-classical': 'classical',
  'armenian-classical': 'classical',
  'azerbaijani-classical': 'classical',
  ballet: 'classical',
  baroque: 'classical',
  'burmese-classical': 'classical',
  'central-asian-classical': 'classical',
  'chamber-folk': 'classical',
  'chamber-jazz': 'classical',
  'chamber-music': 'classical',
  'chamber-pop': 'classical',
  'chinese-classical': 'classical',
  choral: 'classical',
  'classical-fusion': 'classical',
  'court-music': 'classical',
  duduk: 'classical',
  'fijian-choral': 'classical',
  'film-scoring': 'classical',
  'georgian-polyphony': 'classical',
  'hindustani-classical': 'classical',
  impressionism: 'classical',
  'indian-classical': 'classical',
  'iso-polyphony': 'classical',
  'japanese-classical': 'classical',
  'javanese-classical': 'classical',
  'khmer-classical': 'classical',
  'korean-classical': 'classical',
  'malay-classical': 'classical',
  mariachi: 'classical',
  minimalism: 'classical',
  'minimalist-funk': 'classical',
  'moorish-classical': 'classical',
  opera: 'classical',
  orchestral: 'classical',
  'orchestral-jazz': 'classical',
  'ottoman-classical': 'classical',
  'peking-opera': 'classical',
  'persian-classical': 'classical',
  polyphony: 'classical',
  'pygmy-polyphony': 'classical',
  'revolutionary-opera': 'classical',
  romantic: 'classical',
  sacred: 'classical',
  'sacred-music': 'classical',
  'salsa-romantica': 'classical',
  'samoan-choral': 'classical',
  symphonic: 'classical',
  'tajik-classical': 'classical',
  'thai-classical': 'classical',
  'tongan-choral': 'classical',
  'tuvaluan-choral': 'classical',
  'vietnamese-classical': 'classical',
  // ── West African ──
  'afro-caribbean': 'west-african',
  'afro-manding': 'west-african',
  'afro-peruvian': 'west-african',
  'afro-portuguese': 'west-african',
  'afro-psych': 'west-african',
  afrobeat: 'west-african',
  afrobeats: 'west-african',
  'chopped-screwed': 'west-african',
  'coupe-decale': 'west-african',
  'ewe-drumming': 'west-african',
  ghana: 'west-african',
  griot: 'west-african',
  'griot-tradition': 'west-african',
  gumbe: 'west-african',
  highlife: 'west-african',
  hipco: 'west-african',
  hiplife: 'west-african',
  juju: 'west-african',
  'kora-music': 'west-african',
  makossa: 'west-african',
  malipenga: 'west-african',
  mande: 'west-african',
  mbalax: 'west-african',
  morna: 'west-african',
  'somali-music': 'west-african',
  'vodun-music': 'west-african',
  warba: 'west-african',
  yoruba: 'west-african',
  'yoruba-music': 'west-african',
  zouglou: 'west-african',
  // ── East African ──
  benga: 'east-african',
  'bongo-flava': 'east-african',
  ethiopian: 'east-african',
  salegy: 'east-african',
  twarab: 'east-african',
  // ── North African ──
  andalusian: 'north-african',
  chaabi: 'north-african',
  gnawa: 'north-african',
  maluf: 'north-african',
  rai: 'north-african',
  // ── Central African ──
  'congolese-rumba': 'central-african',
  'rumba-congolaise': 'central-african',
  soukous: 'central-african',
  // ── Southern African ──
  kwaito: 'south-african',
  mbaqanga: 'south-african',
  motswako: 'south-african',
  sega: 'south-african',
  'township-jive': 'south-african',
  // ── West Asian ──
  'iraqi-maqam': 'west-asian',
  khaliji: 'west-asian',
  maqam: 'west-asian',
  mugham: 'west-asian',
  shashmaqam: 'west-asian',
  'sufi-music': 'west-asian',
  // ── Central Asian ──
  'throat-singing': 'central-asian',
  // ── South Asian ──
  baul: 'south-asian',
  bollywood: 'south-asian',
  carnatic: 'south-asian',
  filmi: 'south-asian',
  mahraganat: 'south-asian',
  'mardi-gras-indian': 'south-asian',
  qawwali: 'south-asian',
  tabla: 'south-asian',
  // ── East Asian ──
  gagaku: 'east-asian',
  pansori: 'east-asian',
  yayue: 'east-asian',
  // ── Southeast Asian ──
  dangdut: 'southeast-asian',
  gamelan: 'southeast-asian',
  'luk-thung': 'southeast-asian',
  opm: 'southeast-asian',
  xinyao: 'southeast-asian',
  // ── West European ──
  chanson: 'west-european',
  // ── South European ──
  fado: 'south-european',
  'fado-timorense': 'south-european',
  'neapolitan-song': 'south-european',
  rebetiko: 'south-european',
  // ── Caribbean ──
  bouyon: 'caribbean',
  calypso: 'caribbean',
  chutney: 'caribbean',
  junkanoo: 'caribbean',
  kaiso: 'caribbean',
  kompa: 'caribbean',
  punta: 'caribbean',
  soca: 'caribbean',
  steelpan: 'caribbean',
  'vodou-drumming': 'caribbean',
  // ── Indigenous American ──
  andean: 'indigenous-american',
  indigenous: 'indigenous-american',
  'native-american': 'indigenous-american',
  powwow: 'indigenous-american',
  // ── Oceanian ──
  hawaiian: 'oceanian',
  'maori-music': 'oceanian',
  'slack-key-guitar': 'oceanian',
};

/** The globe string as authored → its subgenre id. */
export const TAG_TO_SUBGENRE: Record<string, string> = {
  // ── Rock ──
  'Aboriginal Rock': 'aboriginal-rock',
  'Acid Rock': 'acid-rock',
  Alternative: 'alternative',
  'Alternative Metal': 'alternative-metal',
  'Alternative Rock': 'alternative-rock',
  'Anatolian Rock': 'anatolian-rock',
  'Arabic Indie': 'arabic-indie',
  'Arabic Indie Rock': 'arabic-indie-rock',
  'Art Punk': 'art-punk',
  'Art Rock': 'art-rock',
  'Black Metal': 'black-metal',
  Britpop: 'britpop',
  'Cambodian Rock': 'cambodian-rock',
  'Classic Pop Rock': 'classic-pop-rock',
  'Classic Rock': 'classic-rock',
  'Classic Rock Pop': 'classic-rock-pop',
  'Death Metal': 'death-metal',
  'Desert Rock': 'desert-rock',
  Emo: 'emo',
  Experimental: 'experimental',
  'Extreme Metal': 'extreme-metal',
  'Filipino Rock': 'filipino-rock',
  'Garage Rock': 'garage-rock',
  'Garage Rock Revival': 'garage-rock-revival',
  'Glam Pop': 'glam-pop',
  'Glam Rock': 'glam-rock',
  'Groove Metal': 'groove-metal',
  'Group Sounds': 'group-sounds',
  Grunge: 'grunge',
  'Grunge Rock': 'grunge-rock',
  'Hard Rock': 'hard-rock',
  Hardcore: 'hardcore',
  'Hardcore Punk': 'hardcore-punk',
  'Heartland Rock': 'heartland-rock',
  'Heavy Metal': 'heavy-metal',
  Indie: 'indie',
  'Indie Dance': 'indie-dance',
  'Indie Pop': 'indie-pop',
  'Indie Rock': 'indie-rock',
  'Jam Rock': 'jam-rock',
  'Japanese Rock': 'japanese-rock',
  Krautrock: 'krautrock',
  'Lounge Rock': 'lounge-rock',
  'Malay Rock': 'malay-rock',
  'Math Rock': 'math-rock',
  Merseybeat: 'merseybeat',
  Metal: 'metal',
  Metalcore: 'metalcore',
  'Neo-Psychedelia': 'neo-psychedelia',
  'New Wave': 'new-wave',
  Noise: 'noise',
  'Noise Pop': 'noise-pop',
  'Noise Rock': 'noise-rock',
  'Nu-Metal': 'nu-metal',
  'Political Rock': 'political-rock',
  'Pop Punk': 'pop-punk',
  'Pop Rock': 'pop-rock',
  'Post-Grunge': 'post-grunge',
  'Post-Hardcore': 'post-hardcore',
  'Post-Punk': 'post-punk',
  'Post-Punk Revival': 'post-punk-revival',
  'Post-Rock': 'post-rock',
  'Post-Soviet Rock': 'post-soviet-rock',
  'Progressive Metal': 'progressive-metal',
  'Progressive Rock': 'progressive-rock',
  'Proto-Punk': 'proto-punk',
  Psychedelic: 'psychedelic',
  'Psychedelic Rock': 'psychedelic-rock',
  'Pub Rock': 'pub-rock',
  Punk: 'punk',
  'Punk Rock': 'punk-rock',
  'Punta Rock': 'punta-rock',
  'Raga Rock': 'raga-rock',
  'Riot Grrrl': 'riot-grrrl',
  'Rock and Roll': 'rock-and-roll',
  'Rock en Espa\\u00f1ol': 'rock-en-espa-u00f1ol',
  'Rock en Español': 'rock-en-espanol',
  'Rock Pop': 'rock-pop',
  'Rock & Roll': 'rock-roll',
  'Rock Shuffle': 'rock-shuffle',
  Rockabilly: 'rockabilly',
  'Sad Girl Indie': 'sad-girl-indie',
  Screamo: 'screamo',
  'Shock Rock': 'shock-rock',
  Shoegaze: 'shoegaze',
  'Shuffle Rock': 'shuffle-rock',
  'Soft Rock': 'soft-rock',
  'Southern Rock': 'southern-rock',
  'Straight Eighth Classic Rock': 'straight-eighth-classic-rock',
  'Straight Eighth Pop Rock': 'straight-eighth-pop-rock',
  'Straight Eighth Rock': 'straight-eighth-rock',
  'Thrash Metal': 'thrash-metal',
  'UK Garage': 'uk-garage',
  Zamrock: 'zamrock',
  // ── Pop ──
  'Adult Contemporary': 'adult-contemporary',
  'Afro-Pop': 'afro-pop',
  'Arabian Pop': 'arabian-pop',
  'Arabic Pop': 'arabic-pop',
  'Art Pop': 'art-pop',
  Ballad: 'ballad',
  'Bubblegum Pop': 'bubblegum-pop',
  'C-Pop': 'c-pop',
  'City Pop': 'city-pop',
  'Classic Pop': 'classic-pop',
  Dance: 'dance',
  'Dance Music': 'dance-music',
  'Dance Pop': 'dance-pop',
  'Dark Pop': 'dark-pop',
  'Easy Listening': 'easy-listening',
  Europop: 'europop',
  'Gulf Pop': 'gulf-pop',
  Hyperpop: 'hyperpop',
  'Indonesian Pop': 'indonesian-pop',
  'J-Pop': 'j-pop',
  'Jangle Pop': 'jangle-pop',
  Jingles: 'jingles',
  'K-Pop': 'k-pop',
  'Kenyan Pop': 'kenyan-pop',
  'Khaleeji Pop': 'khaleeji-pop',
  'Khmer Pop': 'khmer-pop',
  'Malaysian Pop': 'malaysian-pop',
  'Mandé Pop': 'mande-pop',
  Mandopop: 'mandopop',
  'Mediterranean Pop': 'mediterranean-pop',
  'Musical Theatre': 'musical-theatre',
  'North Korean Pop': 'north-korean-pop',
  'Persian Pop': 'persian-pop',
  'Polynesian Pop': 'polynesian-pop',
  'Pop Ballad': 'pop-ballad',
  'Pop Ballad Slow Rubato': 'pop-ballad-slow-rubato',
  'Pop Waltz': 'pop-waltz',
  'Power Ballad': 'power-ballad',
  'Power Pop': 'power-pop',
  'Sri Lankan Pop': 'sri-lankan-pop',
  Standards: 'standards',
  'Stick Dance': 'stick-dance',
  'Straight Eighth Pop': 'straight-eighth-pop',
  'Teen Pop': 'teen-pop',
  'Township Pop': 'township-pop',
  'Turkish Pop': 'turkish-pop',
  'UK Dance': 'uk-dance',
  Vaudeville: 'vaudeville',
  'Zulu Pop': 'zulu-pop',
  // ── Funk ──
  'Acoustic Soul': 'acoustic-soul',
  'Afro-Funk': 'afro-funk',
  'Afro-Soul': 'afro-soul',
  'Alternative R&B': 'alternative-r-b',
  'Baile Funk': 'baile-funk',
  'Blue-Eyed Soul': 'blue-eyed-soul',
  'Classic Motown': 'classic-motown',
  'Classic R&B': 'classic-r-b',
  'Classic Soul': 'classic-soul',
  Disco: 'disco',
  'Electro-Funk': 'electro-funk',
  'Folk Soul': 'folk-soul',
  'Funk Pop': 'funk-pop',
  'Funk Rock': 'funk-rock',
  Funky: 'funky',
  'Funky Motown': 'funky-motown',
  'Funky Pop': 'funky-pop',
  'Funky Soul': 'funky-soul',
  'Future Soul': 'future-soul',
  'Go-Go': 'go-go',
  Gospel: 'gospel',
  'Gospel Choir': 'gospel-choir',
  Motown: 'motown',
  'Neo Soul': 'neo-soul',
  'New Orleans Funk': 'new-orleans-funk',
  'New Orleans R&B': 'new-orleans-r-b',
  'P-Funk': 'p-funk',
  'Philadelphia Soul': 'philadelphia-soul',
  'Psychedelic Funk': 'psychedelic-funk',
  'Psychedelic Soul': 'psychedelic-soul',
  'Punk Funk': 'punk-funk',
  'R And B': 'r-and-b',
  Soul: 'soul',
  'Soul R&B': 'soul-r-b',
  'Southern Soul': 'southern-soul',
  'Straight Eighth Funk': 'straight-eighth-funk',
  'Straight Eighth Funky Soul': 'straight-eighth-funky-soul',
  'Thai Funk': 'thai-funk',
  'Tribal Funk': 'tribal-funk',
  Wassoulou: 'wassoulou',
  // ── Folk ──
  Acoustic: 'acoustic',
  'Acoustic Rock': 'acoustic-rock',
  'Afar Folk': 'afar-folk',
  'Alt-Country': 'alt-country',
  Americana: 'americana',
  'Andean Folk': 'andean-folk',
  Appalachian: 'appalachian',
  'Armenian Folk': 'armenian-folk',
  'Bengali Folk': 'bengali-folk',
  'Bhutanese Folk': 'bhutanese-folk',
  Bluegrass: 'bluegrass',
  Celtic: 'celtic',
  'Classic Country': 'classic-country',
  'Classic Folk Rock': 'classic-folk-rock',
  Country: 'country',
  'Country Ballad': 'country-ballad',
  'Country Folk': 'country-folk',
  'Country Pop': 'country-pop',
  'Country Pop Ballad': 'country-pop-ballad',
  'Country Rock': 'country-rock',
  'Fijian Folk': 'fijian-folk',
  'Folk Ballad': 'folk-ballad',
  'Folk Pop': 'folk-pop',
  'Folk Punk': 'folk-punk',
  'Folk Rock': 'folk-rock',
  'Folk Song': 'folk-song',
  'Greek Folk': 'greek-folk',
  'Indie Folk': 'indie-folk',
  'Indie Folk Rock': 'indie-folk-rock',
  'Irish Folk': 'irish-folk',
  'Kazakh Folk': 'kazakh-folk',
  'Kyrgyz Folk': 'kyrgyz-folk',
  'Lebanese Folk': 'lebanese-folk',
  'Maldivian Folk': 'maldivian-folk',
  'Mongolian Folk': 'mongolian-folk',
  'Nauruan Folk': 'nauruan-folk',
  'Nepali Folk': 'nepali-folk',
  'Newari Folk': 'newari-folk',
  'Old-Time': 'old-time',
  'Omani Folk': 'omani-folk',
  'Outlaw Country': 'outlaw-country',
  'Pacific Folk': 'pacific-folk',
  'Pashto Folk': 'pashto-folk',
  Protest: 'protest',
  'Protest Folk': 'protest-folk',
  'Protest Music': 'protest-music',
  'Rodeo Country': 'rodeo-country',
  'Scandinavian Folk': 'scandinavian-folk',
  'Sesotho Traditional': 'sesotho-traditional',
  'Singer-Songwriter': 'singer-songwriter',
  'String Band': 'string-band',
  'Sudanese Folk': 'sudanese-folk',
  'Swazi Traditional': 'swazi-traditional',
  Traditional: 'traditional',
  'Traditional Ballad': 'traditional-ballad',
  'Turbo-Folk': 'turbo-folk',
  'Turkish Folk': 'turkish-folk',
  'Turkmen Folk': 'turkmen-folk',
  'Vietnamese Folk': 'vietnamese-folk',
  Western: 'western',
  'Yemeni Folk': 'yemeni-folk',
  // ── Jazz ──
  'Afro-Fusion': 'afro-fusion',
  'Afro-Jazz': 'afro-jazz',
  Afroswing: 'afroswing',
  'Avant-Garde': 'avant-garde',
  'Avant-Garde Jazz': 'avant-garde-jazz',
  'Azerbaijani Jazz': 'azerbaijani-jazz',
  Bebop: 'bebop',
  'Big Band': 'big-band',
  'Blues Jazz': 'blues-jazz',
  'Cape Jazz': 'cape-jazz',
  'Classic Jazz Pop': 'classic-jazz-pop',
  'Contemporary Jazz': 'contemporary-jazz',
  'Cool Jazz': 'cool-jazz',
  Dixieland: 'dixieland',
  'ECM Jazz': 'ecm-jazz',
  'Ethio-Jazz': 'ethio-jazz',
  'Free Jazz': 'free-jazz',
  'Funk Fusion': 'funk-fusion',
  'Funky Jazz': 'funky-jazz',
  'Funky Jazz Soul': 'funky-jazz-soul',
  'Funky Soul Jazz': 'funky-soul-jazz',
  'Hard Bop': 'hard-bop',
  'Hot Jazz': 'hot-jazz',
  'Jazz Ballad': 'jazz-ballad',
  'Jazz Funk': 'jazz-funk',
  'Jazz Fusion': 'jazz-fusion',
  'Jazz Waltz': 'jazz-waltz',
  'Jazzy Pop': 'jazzy-pop',
  'Modal Jazz': 'modal-jazz',
  'Neo-Bop': 'neo-bop',
  'New Jack Swing': 'new-jack-swing',
  'Post-Bop': 'post-bop',
  Ragtime: 'ragtime',
  'Slow Swing': 'slow-swing',
  'Somali Jazz': 'somali-jazz',
  'Soul Jazz': 'soul-jazz',
  'Spanish-African Fusion': 'spanish-african-fusion',
  'Spiritual Jazz': 'spiritual-jazz',
  Swing: 'swing',
  'Township Jazz': 'township-jazz',
  'Vocal Jazz': 'vocal-jazz',
  'West Coast Jazz': 'west-coast-jazz',
  // ── Hip Hop ──
  'Abstract Hip Hop': 'abstract-hip-hop',
  'African Hip Hop': 'african-hip-hop',
  'Alternative Hip Hop': 'alternative-hip-hop',
  'Brazilian Hip Hop': 'brazilian-hip-hop',
  'Conscious Rap': 'conscious-rap',
  Crunk: 'crunk',
  'Cuban Hip Hop': 'cuban-hip-hop',
  Drill: 'drill',
  'East Coast Rap': 'east-coast-rap',
  'Experimental Hip-Hop': 'experimental-hip-hop',
  'G-Funk': 'g-funk',
  'Gospel Rap': 'gospel-rap',
  Grime: 'grime',
  'Gully Rap': 'gully-rap',
  'Hardcore Rap': 'hardcore-rap',
  'Hip Hop R&B': 'hip-hop-r-b',
  'Hip Hop Soul': 'hip-hop-soul',
  'Indian Hip Hop': 'indian-hip-hop',
  'Indie Hip Hop': 'indie-hip-hop',
  'Japanese Hip Hop': 'japanese-hip-hop',
  'Jazz Rap': 'jazz-rap',
  'K-Hip Hop': 'k-hip-hop',
  'Latin Hip Hop': 'latin-hip-hop',
  'Latin Trap': 'latin-trap',
  'Political Rap': 'political-rap',
  'Pop Rap': 'pop-rap',
  'Psychedelic Rap': 'psychedelic-rap',
  Rap: 'rap',
  'Rap Metal': 'rap-metal',
  'Rap Rock': 'rap-rock',
  'Southern Hip Hop': 'southern-hip-hop',
  Trap: 'trap',
  'UK Drill': 'uk-drill',
  'UK Hip Hop': 'uk-hip-hop',
  'Underground Hip Hop': 'underground-hip-hop',
  'West Coast Hip Hop': 'west-coast-hip-hop',
  // ── Reggae ──
  'Alternative Reggae': 'alternative-reggae',
  'California Reggae': 'california-reggae',
  Dancehall: 'dancehall',
  Dembow: 'dembow',
  Dub: 'dub',
  Dubstep: 'dubstep',
  'European Reggae': 'european-reggae',
  'Funky Reggae': 'funky-reggae',
  'Island Reggae': 'island-reggae',
  'Lovers Rock': 'lovers-rock',
  Maskandi: 'maskandi',
  Mento: 'mento',
  'Pacific Reggae': 'pacific-reggae',
  'Post-Dubstep': 'post-dubstep',
  Ragga: 'ragga',
  'Ragga Soca': 'ragga-soca',
  'Reggae en Espa\\u00f1ol': 'reggae-en-espa-u00f1ol',
  'Reggae Fusion': 'reggae-fusion',
  'Reggae Pop': 'reggae-pop',
  'Reggae Revival': 'reggae-revival',
  Reggaeton: 'reggaeton',
  Rocksteady: 'rocksteady',
  'Roots Reggae': 'roots-reggae',
  'Samba-Reggae': 'samba-reggae',
  Ska: 'ska',
  'Ska Punk': 'ska-punk',
  'Ska Revival': 'ska-revival',
  'Ska Rock': 'ska-rock',
  // ── Latin ──
  'Afro-Cuban': 'afro-cuban',
  'Afro-Cuban Jazz': 'afro-cuban-jazz',
  Bachata: 'bachata',
  Bolero: 'bolero',
  'Bossa Nova': 'bossa-nova',
  'Cha-cha-chá': 'cha-cha-cha',
  Charanga: 'charanga',
  Chicha: 'chicha',
  Cumbia: 'cumbia',
  'Cumbia Peruana': 'cumbia-peruana',
  'Cumbia Rock': 'cumbia-rock',
  'Cumbia Sonidera': 'cumbia-sonidera',
  'Cumbia Villera': 'cumbia-villera',
  Danzón: 'danzon',
  'Electro-Cumbia': 'electro-cumbia',
  Flamenco: 'flamenco',
  'Latin Alternative': 'latin-alternative',
  'Latin Boogaloo': 'latin-boogaloo',
  'Latin Folk': 'latin-folk',
  'Latin Funk': 'latin-funk',
  'Latin Jazz': 'latin-jazz',
  'Latin Pop': 'latin-pop',
  'Latin Rock': 'latin-rock',
  'Latin Urban': 'latin-urban',
  Mambo: 'mambo',
  Merengue: 'merengue',
  MPB: 'mpb',
  Norteño: 'norteno',
  'Nueva Canci\\u00f3n': 'nueva-canci-u00f3n',
  'Nueva Canción': 'nueva-cancion',
  'Nuevo Tango': 'nuevo-tango',
  Ranchera: 'ranchera',
  'Rock Latino': 'rock-latino',
  Salsa: 'salsa',
  Samba: 'samba',
  'Samba de Roda': 'samba-de-roda',
  'Samba Rock': 'samba-rock',
  'Son Cubano': 'son-cubano',
  Tango: 'tango',
  Timba: 'timba',
  Tropicália: 'tropicalia',
  // ── Blues ──
  'Acoustic Blues': 'acoustic-blues',
  'Blues Rock': 'blues-rock',
  'Bluesy Pop': 'bluesy-pop',
  Boogie: 'boogie',
  'British Blues': 'british-blues',
  'Chicago Blues': 'chicago-blues',
  'Classic Blues': 'classic-blues',
  'Country Blues': 'country-blues',
  'Delta Blues': 'delta-blues',
  'Desert Blues': 'desert-blues',
  'Electric Blues': 'electric-blues',
  'Folk Blues': 'folk-blues',
  'Hill Country Blues': 'hill-country-blues',
  'Memphis Blues': 'memphis-blues',
  'Piedmont Blues': 'piedmont-blues',
  'Punk Blues': 'punk-blues',
  'Soul Blues': 'soul-blues',
  'Talking Blues': 'talking-blues',
  'Texas Blues': 'texas-blues',
  'Tuareg Blues': 'tuareg-blues',
  'World Blues': 'world-blues',
  // ── Electronic ──
  'Acid House': 'acid-house',
  Amapiano: 'amapiano',
  Ambient: 'ambient',
  'Ambient Techno': 'ambient-techno',
  'Balearic Beat': 'balearic-beat',
  Downtempo: 'downtempo',
  'Drum and Bass': 'drum-and-bass',
  EDM: 'edm',
  'Electronic Rock': 'electronic-rock',
  Electronica: 'electronica',
  Electropop: 'electropop',
  House: 'house',
  IDM: 'idm',
  Industrial: 'industrial',
  Jungle: 'jungle',
  Kuduro: 'kuduro',
  'Minimal Techno': 'minimal-techno',
  Psytrance: 'psytrance',
  'Synth-Pop': 'synth-pop',
  Techno: 'techno',
  Technopop: 'technopop',
  Trance: 'trance',
  // ── Classical ──
  'Afghan Classical': 'afghan-classical',
  'Andalusi Classical': 'andalusi-classical',
  'Andalusian Classical': 'andalusian-classical',
  'Arabic Classical': 'arabic-classical',
  'Armenian Classical': 'armenian-classical',
  'Azerbaijani Classical': 'azerbaijani-classical',
  Ballet: 'ballet',
  Baroque: 'baroque',
  'Burmese Classical': 'burmese-classical',
  'Central Asian Classical': 'central-asian-classical',
  'Chamber Folk': 'chamber-folk',
  'Chamber Jazz': 'chamber-jazz',
  'Chamber Music': 'chamber-music',
  'Chamber Pop': 'chamber-pop',
  'Chinese Classical': 'chinese-classical',
  Choral: 'choral',
  'Classical Fusion': 'classical-fusion',
  'Court Music': 'court-music',
  Duduk: 'duduk',
  'Fijian Choral': 'fijian-choral',
  'Film Scoring': 'film-scoring',
  'Georgian Polyphony': 'georgian-polyphony',
  'Hindustani Classical': 'hindustani-classical',
  Impressionism: 'impressionism',
  'Indian Classical': 'indian-classical',
  'Iso-Polyphony': 'iso-polyphony',
  'Japanese Classical': 'japanese-classical',
  'Javanese Classical': 'javanese-classical',
  'Khmer Classical': 'khmer-classical',
  'Korean Classical': 'korean-classical',
  'Malay Classical': 'malay-classical',
  Mariachi: 'mariachi',
  Minimalism: 'minimalism',
  'Minimalist Funk': 'minimalist-funk',
  'Moorish Classical': 'moorish-classical',
  Opera: 'opera',
  Orchestral: 'orchestral',
  'Orchestral Jazz': 'orchestral-jazz',
  'Ottoman Classical': 'ottoman-classical',
  'Peking Opera': 'peking-opera',
  'Persian Classical': 'persian-classical',
  Polyphony: 'polyphony',
  'Pygmy Polyphony': 'pygmy-polyphony',
  'Revolutionary Opera': 'revolutionary-opera',
  Romantic: 'romantic',
  Sacred: 'sacred',
  'Sacred Music': 'sacred-music',
  'Salsa Romántica': 'salsa-romantica',
  'Samoan Choral': 'samoan-choral',
  Symphonic: 'symphonic',
  'Tajik Classical': 'tajik-classical',
  'Thai Classical': 'thai-classical',
  'Tongan Choral': 'tongan-choral',
  'Tuvaluan Choral': 'tuvaluan-choral',
  'Vietnamese Classical': 'vietnamese-classical',
  // ── West African ──
  'Afro-Caribbean': 'afro-caribbean',
  'Afro-Manding': 'afro-manding',
  'Afro-Peruvian': 'afro-peruvian',
  'Afro-Portuguese': 'afro-portuguese',
  'Afro-Psych': 'afro-psych',
  Afrobeat: 'afrobeat',
  Afrobeats: 'afrobeats',
  'Chopped & Screwed': 'chopped-screwed',
  'Coupé-Décalé': 'coupe-decale',
  'Ewe Drumming': 'ewe-drumming',
  Ghana: 'ghana',
  Griot: 'griot',
  'Griot Tradition': 'griot-tradition',
  Gumbe: 'gumbe',
  Highlife: 'highlife',
  Hipco: 'hipco',
  Hiplife: 'hiplife',
  Jùjú: 'juju',
  'Kora Music': 'kora-music',
  Makossa: 'makossa',
  Malipenga: 'malipenga',
  Mandé: 'mande',
  Mbalax: 'mbalax',
  Morna: 'morna',
  'Somali Music': 'somali-music',
  'Vodun Music': 'vodun-music',
  Warba: 'warba',
  Yoruba: 'yoruba',
  'Yoruba Music': 'yoruba-music',
  Zouglou: 'zouglou',
  // ── East African ──
  Benga: 'benga',
  'Bongo Flava': 'bongo-flava',
  Ethiopian: 'ethiopian',
  Salegy: 'salegy',
  Twarab: 'twarab',
  // ── North African ──
  Andalusian: 'andalusian',
  Chaabi: 'chaabi',
  Gnawa: 'gnawa',
  "Ma'luf": 'maluf',
  Raï: 'rai',
  // ── Central African ──
  'Congolese Rumba': 'congolese-rumba',
  'Rumba Congolaise': 'rumba-congolaise',
  Soukous: 'soukous',
  // ── Southern African ──
  Kwaito: 'kwaito',
  Mbaqanga: 'mbaqanga',
  Motswako: 'motswako',
  Sega: 'sega',
  'Township Jive': 'township-jive',
  // ── West Asian ──
  'Iraqi Maqam': 'iraqi-maqam',
  Khaliji: 'khaliji',
  Maqam: 'maqam',
  Mugham: 'mugham',
  Shashmaqam: 'shashmaqam',
  'Sufi Music': 'sufi-music',
  // ── Central Asian ──
  'Throat Singing': 'throat-singing',
  // ── South Asian ──
  Baul: 'baul',
  Bollywood: 'bollywood',
  Carnatic: 'carnatic',
  Filmi: 'filmi',
  Mahraganat: 'mahraganat',
  'Mardi Gras Indian': 'mardi-gras-indian',
  Qawwali: 'qawwali',
  Tabla: 'tabla',
  // ── East Asian ──
  Gagaku: 'gagaku',
  Pansori: 'pansori',
  Yayue: 'yayue',
  // ── Southeast Asian ──
  Dangdut: 'dangdut',
  Gamelan: 'gamelan',
  'Luk Thung': 'luk-thung',
  OPM: 'opm',
  Xinyao: 'xinyao',
  // ── West European ──
  Chanson: 'chanson',
  // ── South European ──
  Fado: 'fado',
  'Fado Timorense': 'fado-timorense',
  'Neapolitan Song': 'neapolitan-song',
  Rebetiko: 'rebetiko',
  // ── Caribbean ──
  Bouyon: 'bouyon',
  Calypso: 'calypso',
  Chutney: 'chutney',
  Junkanoo: 'junkanoo',
  Kaiso: 'kaiso',
  Kompa: 'kompa',
  Punta: 'punta',
  Soca: 'soca',
  Steelpan: 'steelpan',
  'Vodou Drumming': 'vodou-drumming',
  // ── Indigenous American ──
  Andean: 'andean',
  Indigenous: 'indigenous',
  'Native American': 'native-american',
  Powwow: 'powwow',
  // ── Oceanian ──
  Hawaiian: 'hawaiian',
  'Māori Music': 'maori-music',
  'Slack-Key Guitar': 'slack-key-guitar',
};

/** Globe strings that are a genre outright. */
export const TAG_TO_GENRE: Record<string, string> = {
  'R&B': 'rnb',
  Blues: 'blues',
  Caribbean: 'caribbean',
  Classical: 'classical',
  Electronic: 'electronic',
  Folk: 'folk',
  Funk: 'funk',
  'Hip Hop': 'hip-hop',
  'Hip-Hop': 'hip-hop',
  'Jam Band': 'jam-band',
  Jazz: 'jazz',
  Latin: 'latin',
  Pop: 'pop',
  Reggae: 'reggae',
  Rock: 'rock',
  'West African': 'west-african',
};

/** Instruments wearing a genre tag. Route these to the instrument graph. */
export const INSTRUMENT_TAGS: readonly string[] = [
  'African Drumming',
  'Dombra',
  'Dutar',
  'Fiddle',
  'Harp Music',
  'Khene Music',
  'Kora',
  'Marimba',
  'Mbira',
  'Oud Music',
  'Panpipe Ensemble',
  'Royal Drumming',
  'Rubab',
  'Saxophone',
];

/** Reach or format, not music. Always accompanied by a real tag. */
export const IGNORED_GENRE_TAGS: readonly string[] = [
  'Call and Response',
  'Compilation',
  'Crossover',
  'Custom Music',
  'Devotional',
  'Diaspora',
  'Disney',
  'Festival',
  'Improvisation',
  'Revival',
  'Ritual',
  'Secular',
  'Session Music',
  'Sound Art',
  'Spoken Word',
  'World',
  'World Music',
];

/** Not placed yet — mostly one event each, from everywhere. Guessing would
 *  put Armenian duduk music in the wrong hemisphere. Most frequent first. */
export const UNPLACED_GENRE_TAGS: readonly string[] = [
  'Brass Band',
  'Lo-Fi',
  'Jamgrass',
  'Trip-Hop',
  'Baltimore Club',
  'Hardstyle',
  'New Beat',
  'EBM',
  'Rave',
  'Madchester',
  'French Touch',
  'Asian Underground',
  'Future Bass',
  'Tarab',
  'Film Music',
  'Gregorian Chant',
  'Thangyat',
  'Makam',
  'Pinpeat',
  'Piphat',
  'Jeongak',
  'Confucian',
  'Dastgah',
  'Nanguan',
  'Mahori',
  'Nha nhac',
  'Odissi',
  'Arabesque',
  'Malouf',
  'Haqiba',
  'Bwiti Music',
  'Balélé',
  'Sai',
  'Guayla',
  'Tigrinya Music',
  'Moutya',
  'Shambo',
  'Sibhaca',
  'Famo',
  'Roma Brass',
  'Muwashah',
  "Al-Ghina Al-San'ani",
  'Liwa',
  'Fijiri',
  'Sawt',
  'Akyns',
  'Falak',
  'Bakhshi',
  'Baila',
  'Rigsar',
  'Bodu Beru',
  'Ca Tru',
  'Lam',
  'Resistance Music',
  'Gulingtangan',
  'Sing-Sing',
  "Fa'ataupati",
  'Lakalaka',
  'Te Bino',
  'Kiribati Chant',
  'Micronesian Chant',
  'Marshallese Chant',
  'Palauan Chant',
  'Omengat Song',
  'Fatele',
  'Acadian',
  'Roots',
  'Candombe',
  'Cowboy Music',
  'Ring Shout',
  'Rara',
  'Candomblé',
  'Afoxé',
  'Axé',
  'Spiritual',
  'Mizrahi',
  'Pacific Island Music',
  'Haka',
  'Spirituals',
  'Operetta',
  'Regional Mexican',
  'Son Nica',
  'Pasillo',
  'Guarania',
  'Landó',
  'Festejo',
  'Contradanza',
  'Lundu',
  'Maxixe',
  'Son Montuno',
  'Pachanga',
  'Guaracha',
  'Mestizo',
  'Tejano',
  'Son Jarocho',
  'Mandingue',
  'Palm Wine',
  'Maringa',
  'Ússua',
  'Socopé',
  'Kadongo Kamu',
  'Mgodro',
  'Seggae',
  'Marrabenta',
  'Chimurenga',
  'Rumba',
  'Songhai',
  'Fula Music',
  'Banku',
  'Tishoumaren',
  'Qaraami',
  'Lounge',
  'Jug Band',
  'African Music',
  'Minneapolis Sound',
  'Dinka Chant',
  'Afrofuturism',
  'Spouge',
  'Goombay',
  'Dennery Segment',
  'Cadence-lypso',
  'Antigua Benna',
  'Kaseko',
  'Kawina',
  'Kumina',
  'Maroon Music',
  'Sound System',
  'DJ Style',
  '2 Tone',
];

const SKIP = new Set([
  ...UNPLACED_GENRE_TAGS,
  ...IGNORED_GENRE_TAGS,
  ...INSTRUMENT_TAGS,
]);

/**
 * Where a globe genre string lands. Null when the tag carries no genre signal,
 * names an instrument, or has not been placed — callers treat that as
 * "unknown", never as a default genre.
 */
export function resolveGenreTag(tag: string): ResolvedGenre | null {
  const clean = tag.trim();
  if (!clean || SKIP.has(clean)) return null;
  const direct = TAG_TO_GENRE[clean];
  if (direct) return { genre: direct };
  const subgenre = TAG_TO_SUBGENRE[clean];
  if (!subgenre) return null;
  const genre = SUBGENRE_PARENT[subgenre];
  return genre && getGenre(genre) ? { genre, subgenre } : null;
}
