import { readFileSync, writeFileSync } from 'node:fs';
import { format, resolveConfig } from 'prettier';
import { describe, expect, it } from 'vitest';
import { makeDecision } from '@/content/suggestions/status';
import type { Suggestion } from '@/content/suggestions/types';
import { generateSuggestionSchema } from '@/scripts/apiContract/generateSuggestionSchema';
import {
  suggestionDecisionSchema,
  suggestionSchema,
} from '@/scripts/apiContract/suggestionSchema';

/**
 * The suggestion contract, kept honest the same two ways as the bodies':
 * the committed schema is regenerated from the type file and must match, and
 * what the importer and the console write must pass it.
 */

const OUT = 'src/scripts/apiContract/suggestionSchema.ts';

const pretty = async (source: string) =>
  format(source, { ...(await resolveConfig(OUT)), parser: 'typescript' });

const SUGGESTION: Suggestion = {
  id: '597d0fc572bfeef5',
  target: { kind: 'artist', slug: '4-non-blondes' },
  path: 'basedInPlaceId',
  op: 'set',
  value: 'san-francisco',
  display: 'Formed in San Francisco',
  sources: [
    {
      provider: 'musicbrainz',
      url: 'https://musicbrainz.org/area/83f22bb6-4631-443c-bace-9fae8540362a',
      label: 'begin-area',
    },
    { provider: 'app', label: 'artist_location "4 non blondes"' },
  ],
  evidence: ['MusicBrainz begin-area San Francisco'],
  confidence: 0.95,
  tier: 'sure',
  requires: [
    {
      kind: 'globe_city',
      slug: 'san-francisco',
      body: { id: 'san-francisco', name: 'San Francisco', pin: false },
    },
  ],
  dependsOn: '25baa8b72910a867',
  batch: 'mb-2026-09-30',
};

describe('the generated suggestion schema', () => {
  it('matches what the type file says today', async () => {
    const wanted = await pretty(
      generateSuggestionSchema({
        name: 'suggestions/types.ts',
        text: readFileSync('src/content/suggestions/types.ts', 'utf8'),
      }),
    );
    if (process.env.WRITE_CONTRACT) writeFileSync(OUT, wanted);
    expect(readFileSync(OUT, 'utf8')).toBe(wanted);
  });

  it('takes a suggestion and every decision about it, and nothing else', () => {
    expect(suggestionSchema.safeParse(SUGGESTION).success).toBe(true);
    const at = '2026-10-01T12:00:00.000Z';
    for (const op of ['accept', 'reject', 'drop', 'review'] as const)
      expect(
        suggestionDecisionSchema.safeParse(
          makeDecision(SUGGESTION, op, { by: 'admin-1', at, method: 'bulk' }),
        ).success,
        op,
      ).toBe(true);
    const replace = makeDecision(SUGGESTION, 'replace', {
      by: 'admin-1',
      at,
      method: 'single',
      seen: 'washington',
    });
    expect(replace.seenHash).toMatch(/^[0-9a-f]{16}$/);
    expect(suggestionDecisionSchema.safeParse(replace).success).toBe(true);

    // Strict, as the body schemas are: an unknown field is refused, and so
    // is a value outside a union.
    expect(
      suggestionSchema.safeParse({ ...SUGGESTION, note: 'x' }).success,
    ).toBe(false);
    expect(
      suggestionSchema.safeParse({ ...SUGGESTION, tier: 'weak' }).success,
    ).toBe(false);
    expect(
      suggestionSchema.safeParse({
        ...SUGGESTION,
        sources: [{ provider: 'discogs' }],
      }).success,
    ).toBe(false);
    expect(
      suggestionDecisionSchema.safeParse({ ...replace, op: 'undo' }).success,
    ).toBe(false);
  });

  it('takes every row the importer has committed', async () => {
    // The artifacts are generated by the importer and may not be there yet.
    const files = import.meta.glob<string>(
      '/src/scripts/enrichment/suggestions/*.json',
      { query: '?raw', import: 'default' },
    );
    for (const [path, load] of Object.entries(files)) {
      const parsed = JSON.parse(await load()) as { suggestions?: unknown[] };
      if (!Array.isArray(parsed.suggestions)) continue;
      const refused = parsed.suggestions.filter(
        (row) => !suggestionSchema.safeParse(row).success,
      );
      expect(refused.slice(0, 3), path).toEqual([]);
    }
  });
});
