/**
 * Generate src/components/atlas/data/stateBoundaries.ts — simplified US state
 * and Canadian province outlines, for deciding which state an event is in.
 *
 * Why this exists: ~80 US/Canadian events happen in towns the CITIES list does
 * not name (Dayton, Buffalo, Raleigh…). Guessing their state from the nearest
 * named city put a quarter of them across the border — the Ohio Players in
 * Indiana, Buffalo in Pennsylvania. Real outlines settle it.
 *
 * Source is the same Natural Earth admin-1 file the globe draws its state
 * polygons from (GEOJSON_URLS.admin1), so the state a panel names is always the
 * shape highlighted on the globe. The globe fetches it at runtime; this copy is
 * static because the matcher runs synchronously, in tests too.
 *
 * Usage:  node src/scripts/buildStateBoundaries.mjs
 * NOT shipped to the browser — development-only.
 */

import fs from 'fs';
import path from 'path';
import process from 'process';
import { fileURLToPath } from 'url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const OUT = path.resolve(HERE, '../components/atlas/data/stateBoundaries.ts');
const SOURCE =
  'https://cdn.jsdelivr.net/gh/nvkelso/natural-earth-vector@master/geojson/ne_50m_admin_1_states_provinces.geojson';

/** Simplification tolerance in degrees (~4km) — far below any town spacing. */
const TOLERANCE = 0.04;
/** Rings smaller than this (deg²) are islets no event sits on. */
const MIN_RING_AREA = 0.0005;

function perpendicularDistance([x, y], [x1, y1], [x2, y2]) {
  const dx = x2 - x1;
  const dy = y2 - y1;
  if (dx === 0 && dy === 0) return Math.hypot(x - x1, y - y1);
  return Math.abs(dy * x - dx * y + x2 * y1 - y2 * x1) / Math.hypot(dx, dy);
}

/** Douglas–Peucker, iterative so long coastlines do not blow the stack. */
function simplify(points) {
  if (points.length < 4) return points;
  const keep = new Uint8Array(points.length);
  keep[0] = keep[points.length - 1] = 1;
  const stack = [[0, points.length - 1]];
  while (stack.length) {
    const [a, b] = stack.pop();
    let max = 0;
    let index = -1;
    for (let i = a + 1; i < b; i++) {
      const d = perpendicularDistance(points[i], points[a], points[b]);
      if (d > max) {
        max = d;
        index = i;
      }
    }
    if (max > TOLERANCE && index !== -1) {
      keep[index] = 1;
      stack.push([a, index], [index, b]);
    }
  }
  return points.filter((_, i) => keep[i]);
}

function ringArea(ring) {
  let sum = 0;
  for (let i = 0, j = ring.length - 1; i < ring.length; j = i++) {
    sum += (ring[j][0] - ring[i][0]) * (ring[j][1] + ring[i][1]);
  }
  return Math.abs(sum / 2);
}

const res = await fetch(SOURCE);
if (!res.ok) throw new Error(`fetch failed: ${res.status}`);
const data = await res.json();

const regions = [];
for (const feature of data.features) {
  const iso = feature.properties?.iso_a2;
  if (iso !== 'US' && iso !== 'CA') continue;
  const name = feature.properties.name;
  const geometry = feature.geometry;
  const polygons =
    geometry.type === 'Polygon' ? [geometry.coordinates] : geometry.coordinates;

  const rings = [];
  for (const polygon of polygons) {
    // Outer ring only: no US state or province has a hole an event sits in.
    const outer = polygon[0];
    if (ringArea(outer) < MIN_RING_AREA) continue;
    const simplified = simplify(outer).map(([lng, lat]) => [
      Math.round(lng * 100) / 100,
      Math.round(lat * 100) / 100,
    ]);
    if (simplified.length >= 4) rings.push(simplified.flat());
  }
  if (rings.length) {
    regions.push({
      name,
      country: iso === 'CA' ? 'Canada' : 'United States',
      rings,
    });
  }
}
regions.sort((a, b) => a.name.localeCompare(b.name));

const body = regions
  .map(
    (r) =>
      `  {\n    name: ${JSON.stringify(r.name)},\n    country: '${r.country}',\n    rings: [\n${r.rings
        .map((ring) => `      [${ring.join(',')}],`)
        .join('\n')}\n    ],\n  },`,
  )
  .join('\n');

fs.writeFileSync(
  OUT,
  `/* eslint-disable */
/**
 * US state and Canadian province outlines, simplified to ~4km.
 *
 * GENERATED by src/scripts/buildStateBoundaries.mjs from Natural Earth admin-1
 * (the same file the globe draws). Do not edit by hand — re-run the script.
 * Listed in .prettierignore: formatted, it is one number per line.
 *
 * Each ring is a flat [lng, lat, lng, lat, …] array (outer rings only).
 */
export interface StateBoundary {
  name: string;
  country: 'United States' | 'Canada';
  rings: number[][];
}

export const STATE_BOUNDARIES: StateBoundary[] = [
${body}
];
`,
);

const points = regions.reduce(
  (n, r) => n + r.rings.reduce((m, ring) => m + ring.length / 2, 0),
  0,
);
console.log(
  `${regions.length} regions, ${points} points → ${path.relative(process.cwd(), OUT)}`,
);
console.log(`${(fs.statSync(OUT).size / 1024).toFixed(0)} KB`);
