// UNISON — Universal music intelligence engine
// Public API

export {
  detectKey,
  analyzeHarmony,
  matchProgressions,
  analyzeRhythm,
  analyzeMelody,
  analyzeVoiceLeading,
  estimateBpm,
  analyzeTimbre,
  analyzeMix,
} from './engine';

export {
  sessionToUnison,
  unisonToMidi,
  unisonToEvents,
  midiToUnison,
  importMidiFileAsUnison,
  audioToUnison,
  musicXmlToUnison,
  importMusicXmlFileAsUnison,
  leadSheetToUnison,
  unisonToLeadSheet,
} from './converters';
export type {
  SessionSnapshot,
  MidiToUnisonOptions,
  AudioToUnisonOptions,
  AudioBufferLike,
  MusicXmlToUnisonOptions,
  LeadSheetToUnisonOptions,
  LeadSheetSnapshot,
  LeadSheetData,
} from './converters';

export type {
  UnisonDocument,
  UnisonMetadata,
  UnisonTrack,
  UnisonNoteEvent,
  UnisonCCEvent,
  UnisonAnalysis,
  KeyDetection,
  AlternateKey,
  UnisonChordRegion,
  ProgressionMatchResult,
  RhythmAnalysis,
  MelodyAnalysis,
  TimbreAnalysis,
  MixAnalysis,
  TrackRole,
  Subdivision,
  MelodyContour,
  VoiceLeadingTransition,
  VoiceLeadingSummary,
  UnisonLyricEvent,
  FormAnalysis,
  FormSection,
  FormRepeat,
  SectionType,
  SpectralFingerprint,
  EnvelopeEstimate,
  InstrumentGuess,
  StereoFieldAnalysis,
  DynamicRangeAnalysis,
  FrequencyBand,
  SpectralBalanceAnalysis,
  LoudnessPoint,
  LoudnessProfile,
} from './types';
