// UNISON — Universal music intelligence engine
// Public API

export {
  detectKey,
  analyzeHarmony,
  matchProgressions,
  analyzeRhythm,
  analyzeMelody,
  analyzeVoiceLeading,
  estimateBpm,
  analyzeTimbre,
  analyzeMix,
  renderVoicing,
  applyVoicingsToTimeline,
  listAvailableGenreLevels,
  renderComping,
  applyComping,
  listCompingPatternsForGenre,
  renderBass,
  applyBass,
  listBassContours,
  listBassRhythmsForGenre,
  renderDrums,
  applyDrums,
  listDrumGenres,
  renderMelody,
  applyMelody,
  parseStyle,
  arrangeForStyle,
} from './engine';
export type {
  VoicingRenderResult,
  RenderVoicingOptions,
  ApplyVoicingsOptions,
  RenderCompingOptions,
  RenderBassOptions,
  RenderDrumsOptions,
  MelodyConfig,
  RenderMelodyOptions,
  ParsedStyle,
  ArrangeForStyleOptions,
  ArrangeResult,
} from './engine';

export {
  sessionToUnison,
  unisonToMidi,
  unisonToEvents,
  midiToUnison,
  importMidiFileAsUnison,
  audioToUnison,
  musicXmlToUnison,
  importMusicXmlFileAsUnison,
  leadSheetToUnison,
  unisonToLeadSheet,
  songToUnison,
} from './converters';
export type {
  SessionSnapshot,
  MidiToUnisonOptions,
  AudioToUnisonOptions,
  AudioBufferLike,
  MusicXmlToUnisonOptions,
  LeadSheetToUnisonOptions,
  LeadSheetSnapshot,
  LeadSheetData,
  SongToUnisonOptions,
} from './converters';

export type {
  UnisonDocument,
  UnisonMetadata,
  UnisonTrack,
  UnisonNoteEvent,
  UnisonCCEvent,
  UnisonAnalysis,
  KeyDetection,
  AlternateKey,
  UnisonChordRegion,
  ProgressionMatchResult,
  RhythmAnalysis,
  MelodyAnalysis,
  TimbreAnalysis,
  MixAnalysis,
  TrackRole,
  Subdivision,
  MelodyContour,
  VoiceLeadingTransition,
  VoiceLeadingSummary,
  UnisonLyricEvent,
  FormAnalysis,
  FormSection,
  FormRepeat,
  SectionType,
  SpectralFingerprint,
  EnvelopeEstimate,
  InstrumentGuess,
  StereoFieldAnalysis,
  DynamicRangeAnalysis,
  FrequencyBand,
  SpectralBalanceAnalysis,
  LoudnessPoint,
  LoudnessProfile,
} from './types';
