/**
 * Rebuild the influence graph in src/components/atlas/data/eventConnections.ts
 * from the 2026-09 review.
 *
 * Two separate jobs:
 *
 * 1. THE GENERATED BLOCK. `src/scripts/buildSongConnections.mjs` matched every
 *    song event to up to two historical events on nothing more than a genre
 *    FAMILY overlap, a <=30 year gap and a shared city OR country. Reviewed
 *    link by link, 905 of its 1,123 edges were judged spurious — a Phish side
 *    project "influencing" a Britney Spears single, a Spice Girls event
 *    "influencing" Hava Nagila. Keep-rate 17-21% across five independent
 *    batches. The block is replaced by the 217 edges that survived review AND
 *    are chronologically possible; they are ordinary curated data from here on.
 *
 *    The generator leaned on song years that were themselves wrong (filled from
 *    MusicBrainz "earliest release by artist", which caught reissues), so
 *    fixing the years first — applyYearFixes.mjs — is what exposed the rest.
 *
 * 2. THE CURATED BLOCK. 44 hand-authored edges run backwards in time, which the
 *    recursive arc walk and the "Influenced by" pills both read as a lineage.
 *    Each carries the reviewer's own verdict: remove, flip, or re-source to a
 *    different event. A retarget is applied to whichever end makes the edge
 *    chronological again.
 *
 * Everything removed is written to docs/globe-review/removed-connections.md so
 * a curator can re-author the real relationship where one exists.
 *
 * Usage: node src/scripts/globe-corrections/applyConnectionFixes.mjs [--dry-run]
 */
import fs from 'node:fs';
import path from 'node:path';

const ROOT = process.cwd();
const FILE = path.join(ROOT, 'src/components/atlas/data/eventConnections.ts');
const DRY = process.argv.includes('--dry-run');

const plan = JSON.parse(
  fs.readFileSync(path.join(import.meta.dirname, 'conn-plan.json'), 'utf8'),
);
const issues = JSON.parse(
  fs.readFileSync(path.join(import.meta.dirname, 'review-issues.json'), 'utf8'),
).filter((i) => i.kind === 'connection');

// Event years, read straight out of the data files (no TS toolchain needed).
const EVENTS_DIR = path.join(ROOT, 'src/components/atlas/data/events');
const year = new Map();
for (const file of fs.readdirSync(EVENTS_DIR)) {
  if (!file.endsWith('.ts') || file === 'index.ts') continue;
  const text = fs.readFileSync(path.join(EVENTS_DIR, file), 'utf8');
  const re = /id: '([^']+)',\s*\n\s*year: (\d{3,4}),/g;
  let m;
  while ((m = re.exec(text))) year.set(m[1], Number(m[2]));
}

const src = fs.readFileSync(FILE, 'utf8');
const BEGIN =
  '  // ── BEGIN auto-generated song connections (buildSongConnections.mjs)';
const beginAt = src.indexOf(BEGIN);
// The generator never wrote its END marker, so the block simply runs to the
// close of the EVENT_CONNECTIONS array literal.
const endAt = src.indexOf('\n];', beginAt);
if (beginAt === -1) {
  // The marker is gone once the block has been replaced, which makes this
  // script safely single-use rather than silently destructive on a re-run.
  console.log('Already applied: the generated block is no longer present.');
  process.exit(0);
}
if (endAt === -1) {
  console.error('Found the block start but not the end of EVENT_CONNECTIONS.');
  process.exit(1);
}

const split = (k) => {
  const [from, to] = k.split('->');
  return { from, to };
};
const chrono = ({ from, to }) =>
  year.has(from) && year.has(to) && year.get(from) <= year.get(to);

const removed = [];

// ── 1. Replace the generated block ────────────────────────────────────────
const aKeep = plan.aKeep.map(split);
const bKeep = plan.bKeep.map(split).map((c) => {
  // The song->song generator sorted strictly by year, so every edge it emitted
  // backwards was a symptom of a wrong year. With the years corrected, the
  // relationship is right and only its direction was inverted.
  if (!chrono(c) && year.has(c.from) && year.has(c.to)) {
    return { from: c.to, to: c.from };
  }
  return c;
});
const cKeep = plan.cKeep.map(split);

const fmt = (list) =>
  list.map((c) => `  { from: '${c.from}', to: '${c.to}' },`).join('\n');

const block = [
  '  // ── Song-library influence links ──────────────────────────────────────',
  '  //',
  '  // Formerly generated by src/scripts/buildSongConnections.mjs. That script',
  '  // matched on a genre family, a 30-year window and a shared country, which',
  '  // produced far more wrong links than right ones (17-21% kept on review).',
  '  // What follows is the reviewed remainder, now hand-maintained: add a link',
  '  // here only when the influence is documented or the artists/labels/scene',
  '  // genuinely connect. The generator must not be re-run against this file.',
  '',
  `  // Historical event → song (${aKeep.length} kept of 1,123 generated)`,
  fmt(aKeep),
  '',
  `  // Song → later song, same artist or a real cover (${bKeep.length})`,
  fmt(bKeep),
  '',
  `  // Song → historical event it catalysed, hand-curated (${cKeep.length})`,
  fmt(cKeep),
].join('\n');

let out = src.slice(0, beginAt) + block + src.slice(endAt);

// ── 2. Curated block: apply each reviewer verdict ─────────────────────────
const verdictFor = (ref) => {
  const texts = issues
    .filter((i) => i.ref === ref)
    .map((i) => String(i.proposed));
  const joined = texts.join(' | ');
  if (/^remove/i.test(joined)) return { kind: 'remove' };
  if (/^flip|keep-only/i.test(joined)) return { kind: 'flip' };
  const rt = /retarget:([a-z0-9-]+)/i.exec(joined);
  if (rt) return { kind: 'retarget', target: rt[1] };
  return { kind: 'none' };
};

// Entries appear either on one line (`{ from: 'a', to: 'b' },`) or wrapped over
// four by prettier when the ids are long, so match within a single object
// literal rather than assuming a layout.
const edgeRe = (from, to) =>
  new RegExp(
    `\\n\\s*\\{[^{}]*?from: '${from}',[^{}]*?to: '${to}',?[^{}]*?\\},`,
  );

const applied = { remove: 0, flip: 0, retarget: 0, unresolved: 0 };

for (const ref of plan.curBack) {
  const { from, to } = split(ref);
  const verdict = verdictFor(ref);
  const re = edgeRe(from, to);
  const match = re.exec(out);
  if (!match) {
    console.warn('  could not locate edge:', ref);
    continue;
  }

  let replacement = null;
  if (verdict.kind === 'flip') {
    replacement = `\n  { from: '${to}', to: '${from}' },`;
    applied.flip++;
  } else if (verdict.kind === 'retarget' && year.has(verdict.target)) {
    // Apply to whichever end restores chronological order.
    const asTo = { from, to: verdict.target };
    const asFrom = { from: verdict.target, to };
    const pick = chrono(asTo) ? asTo : chrono(asFrom) ? asFrom : null;
    if (pick) {
      replacement = `\n  { from: '${pick.from}', to: '${pick.to}' },`;
      applied.retarget++;
    }
  }

  if (replacement === null) {
    removed.push({
      ref,
      why:
        verdict.kind === 'none'
          ? 'runs backwards in time after the year corrections; no reviewed replacement'
          : 'reviewed as not a real influence',
    });
    applied[verdict.kind === 'none' ? 'unresolved' : 'remove']++;
    out = out.slice(0, match.index) + out.slice(match.index + match[0].length);
  } else {
    out =
      out.slice(0, match.index) +
      replacement +
      out.slice(match.index + match[0].length);
  }
}

// Everything the review dropped from the generated block, for the record.
const droppedGenerated = issues
  .filter((i) => /^remove/i.test(String(i.proposed)))
  .map((i) => i.ref)
  .filter((ref) => !plan.curBack.includes(ref));

if (!DRY) {
  fs.writeFileSync(FILE, out);
  const docs = path.join(ROOT, 'docs/globe-review');
  fs.mkdirSync(docs, { recursive: true });
  fs.writeFileSync(
    path.join(docs, 'removed-connections.md'),
    [
      '# Influence links removed in the 2026-09 review',
      '',
      'Each line is an edge that used to appear as an "Influenced by" / "Influenced"',
      'pill and as an arc on the globe. Re-add any of them to `eventConnections.ts`',
      'if the real relationship can be sourced — the point of removing them was that',
      'they were asserted, not established.',
      '',
      `## Hand-curated edges that ran backwards in time (${removed.length})`,
      '',
      ...removed.map((r) => `- \`${r.ref}\` — ${r.why}`),
      '',
      `## Machine-generated edges dropped on review (${droppedGenerated.length})`,
      '',
      'These came from `buildSongConnections.mjs`, which paired songs and events on',
      'a loose genre/era/country heuristic. Listed for completeness; almost none of',
      'them describe a real influence.',
      '',
      ...droppedGenerated.map((ref) => `- \`${ref}\``),
      '',
    ].join('\n'),
  );
}

console.log(
  `${DRY ? '[dry-run] ' : ''}generated block: ${aKeep.length} + ${bKeep.length} + ${cKeep.length} kept (was 1,123 + 279 + 21)`,
);
console.log(
  `  curated backwards edges — removed ${applied.remove}, flipped ${applied.flip}, re-sourced ${applied.retarget}, removed unresolved ${applied.unresolved}`,
);
console.log(
  `  review list: ${removed.length} curated + ${droppedGenerated.length} generated`,
);
