/**
 * Phase 11 — Assessment Engine.
 *
 * Top-level evaluation function that dispatches to the appropriate matcher
 * and returns a scored result.
 *
 * Assessment types escalate in difficulty:
 *   1. pitch_only       — just get the right notes (any order)
 *   2. pitch_order      — right notes in right order
 *   3. pitch_order_timing — add timing accuracy (±200ms)
 *   4. pitch_order_timing_duration — add duration accuracy (±300ms)
 */

import type { ContinuousPerformanceScore } from '@/learn/audio/v2/types';
import {
  type AssessmentType,
  type MatchResult,
  matchPitchOnly,
  matchPitchOrder,
  matchPitchOrderTiming,
  matchPitchOrderTimingDuration,
} from './assessmentMatchers';
import { calculateScore, type AssessmentScore } from './assessmentScoring';
import type { ReceivedNote } from './continuousMatchers';
import { scoreContinuous } from './continuousScoring';
import type { MidiNoteEvent } from './melodyPipeline';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface AssessmentResult {
  /** The assessment type used */
  type: AssessmentType;
  /** Detailed match results per note */
  matchResult: MatchResult;
  /** Overall score with grade and pass/fail */
  score: AssessmentScore;
}

// ---------------------------------------------------------------------------
// Main evaluation function
// ---------------------------------------------------------------------------

/**
 * Evaluate student MIDI input against expected events.
 *
 * @param expected - The target note events generated by the content pipeline
 * @param received - The student's played note events (from MIDI or audio input)
 * @param type - Assessment type (escalating difficulty)
 * @param tempo - Tempo in BPM (required for timing-based assessments)
 * @param timingToleranceMs - Override timing tolerance (default 200ms)
 * @param durationToleranceMs - Override duration tolerance (default 300ms)
 * @returns Complete assessment result with match details and score
 */
export function evaluate(
  expected: MidiNoteEvent[],
  received: MidiNoteEvent[],
  type: AssessmentType,
  tempo: number = 120,
  timingToleranceMs: number = 200,
  durationToleranceMs: number = 300,
): AssessmentResult {
  let matchResult: MatchResult;

  switch (type) {
    case 'pitch_only':
      matchResult = matchPitchOnly(expected, received);
      break;

    case 'pitch_order':
      matchResult = matchPitchOrder(expected, received);
      break;

    case 'pitch_order_timing':
      matchResult = matchPitchOrderTiming(
        expected,
        received,
        tempo,
        timingToleranceMs,
      );
      break;

    case 'pitch_order_timing_duration':
      matchResult = matchPitchOrderTimingDuration(
        expected,
        received,
        tempo,
        timingToleranceMs,
        durationToleranceMs,
      );
      break;
  }

  const score = calculateScore(matchResult, type, tempo);

  return {
    type,
    matchResult,
    score,
  };
}

// ---------------------------------------------------------------------------
// V2 continuous evaluation
// ---------------------------------------------------------------------------

export interface ContinuousAssessmentResult {
  type: AssessmentType;
  continuous: ContinuousPerformanceScore;
  score: AssessmentScore;
}

/**
 * Evaluate using the v2 continuous scoring system.
 * Returns both the rich continuous result and a backward-compatible AssessmentScore.
 */
export function evaluateContinuous(
  expected: MidiNoteEvent[],
  received: ReceivedNote[],
  type: AssessmentType,
  tempo: number = 120,
): ContinuousAssessmentResult {
  const { continuous, legacy } = scoreContinuous(
    expected,
    received,
    tempo,
    type,
  );

  return {
    type,
    continuous,
    score: legacy,
  };
}

// Re-export types for convenience
export type { AssessmentType, MatchResult, AssessmentScore };
