/**
 * Halftone screen geometry: the dot lattice for one ink, and the threshold tile that turns a
 * greyscale coverage value into hard dots. Transcribed from upstream `prints/workings/index.html`
 * (the `buildScreen` block).
 *
 * WHY THIS IS A SEPARATE, PURE MODULE: this is the hardest arithmetic in the engine, and it is the
 * arithmetic that decides every screened pixel. Keeping it free of canvas and DOM means it can be
 * unit-tested in Node against a golden fixture before a single pixel exists — a threshold tile that
 * drifts in the last bit is otherwise only visible as a whole-canvas sha256 mismatch with no clue
 * as to which of a dozen stages moved. `canvas/screens.ts` wraps this and adds the CanvasPattern
 * cache (upstream's `patterns: new Map()`), which is the only canvas-side part of `buildScreen`.
 *
 * WHY A RATIONAL TANGENT: for screen angle tanθ = b/a the lattice is generated by the orthogonal
 * vectors P/√(a²+b²)·(a,b) and P/√(a²+b²)·(−b,a). Walking a of the first and b of the second lands
 * on (P√(a²+b²), 0) — an exactly axis-aligned lattice point. So the square of side
 * S = P√(a²+b²) is a true period of the rotated grid: it tiles the plane seamlessly and holds
 * exactly a²+b² dots. An irrational tangent (a nominal 15°/45°/75°, say) never closes like this,
 * and the tile wrap shows as a visible seam. This is why SCREEN stores {a, b} and not degrees.
 *
 * Screens are anchored to canvas space, never to the object being drawn. A screen that rides along
 * with its subject makes the texture crawl, which is the single most recognisable way this look
 * goes wrong.
 *
 * TRAPS:
 *  - `P` is the EFFECTIVE pitch, S/√n, recovered after S is rounded to whole pixels. It is not
 *    PITCH. Every threshold in the tile is measured against P, so substituting PITCH shifts the
 *    whole tonal response.
 *  - The `pts` dedupe is an epsilon scan over the array built so far, so it is ORDER DEPENDENT:
 *    which representative of a near-duplicate pair survives depends on the m/k visit order. A Set
 *    or a rounded map key is not the same function. Transcribed verbatim.
 *  - Because of that, `pts.length` is NOT always a²+b². The dedupe compares raw coordinates, not
 *    toroidal distance, so a lattice point that lands on the far edge at S-1e-15 instead of 0
 *    survives as a near-duplicate: green/indigo yield 4 points for n=2 and blue/pink 19 for n=17,
 *    each with one or two seam ghosts. This is upstream's behaviour and it is harmless (`wrapped`
 *    already replicates every dot on all four edges, so `th` is unaffected and the pattern tile
 *    just strokes one dot twice). Do NOT "fix" the count — it would change the draw order in
 *    canvas/screens.ts.
 *  - `th` is a Float32Array. The narrowing to f32 is load-bearing at the comparison in inkPass.
 */
import { PITCH, SCREEN, type Ink } from './constants.ts';
import { clamp } from './num.ts';
import type { Pt } from './pt.ts';

/** A lattice point, [x, y]. Mutable: upstream builds these by push and reads them positionally. */

export interface ScreenTile {
  /** Tile side in device px — a whole number of pixels, and a true period of the dot lattice. */
  S: number;
  /** Effective pitch after S was rounded: S/√n, not PITCH. */
  P: number;
  /** Dot centres reduced into [0,S)² — a²+b² of them, plus any seam ghosts (see header). */
  pts: Pt[];
  /** `pts` plus its 8 neighbouring copies, so dots straddling an edge are drawn on both sides. */
  wrapped: Pt[];
  /** S×S row-major coverage thresholds in [0,1]. A pixel takes ink when coverage exceeds th. */
  th: Float32Array;
}

export function buildScreenTile(name: Ink): ScreenTile {
  const { a, b } = SCREEN[name];
  const n = a * a + b * b;
  const S = Math.max(2, Math.round(PITCH * Math.sqrt(n)));
  const P = S / Math.sqrt(n); // effective pitch after rounding
  const u = P / Math.sqrt(n);
  const v1 = [u * a, u * b],
    v2 = [-u * b, u * a];

  // Lattice points reduced into the tile, plus wrapped neighbours so dots that
  // straddle an edge are drawn on both sides.
  const pts: Pt[] = [];
  for (let m = -n; m <= n; m++) {
    for (let k = -n; k <= n; k++) {
      const x = m * v1[0] + k * v2[0],
        y = m * v1[1] + k * v2[1];
      const wx = ((x % S) + S) % S,
        wy = ((y % S) + S) % S;
      if (
        !pts.some(
          (p) => Math.abs(p[0] - wx) < 0.01 && Math.abs(p[1] - wy) < 0.01,
        )
      )
        pts.push([wx, wy]);
    }
  }
  const wrapped: Pt[] = [];
  for (const [x, y] of pts)
    for (const dx of [-S, 0, S])
      for (const dy of [-S, 0, S]) wrapped.push([x + dx, y + dy]);

  // Threshold tile: a pixel takes ink when coverage exceeds π·d²/P², which is
  // the coverage at which a dot of radius d would reach that pixel.
  const th = new Float32Array(S * S);
  for (let y = 0; y < S; y++) {
    for (let x = 0; x < S; x++) {
      let d2 = Infinity;
      for (const [px, py] of wrapped) {
        const dx = x + 0.5 - px,
          dy = y + 0.5 - py,
          q = dx * dx + dy * dy;
        if (q < d2) d2 = q;
      }
      th[y * S + x] = clamp((Math.PI * d2) / (P * P), 0, 1);
    }
  }
  return { S, P, pts, wrapped, th };
}
