/**
 * Maps Globe event genres to the 8 Learn course categories.
 * Two-pass lookup: exact match first, then substring match.
 */

export type LearnCourse = 'Pop' | 'Folk' | 'Rock' | 'R&B' | 'Jazz' | 'Classical' | 'Electronic' | 'Hip Hop'

const GENRE_TO_COURSE: Record<string, LearnCourse> = {
  // ── Direct matches ──
  'Pop': 'Pop',
  'Rock': 'Rock',
  'Jazz': 'Jazz',
  'Classical': 'Classical',
  'Electronic': 'Electronic',
  'Hip Hop': 'Hip Hop',
  'Folk': 'Folk',
  'R&B': 'R&B',

  // ── Pop family ──
  'K-Pop': 'Pop',
  'J-Pop': 'Pop',
  'City Pop': 'Pop',
  'C-Pop': 'Pop',
  'Mandopop': 'Pop',
  'Synth-Pop': 'Pop',
  'Synth Pop': 'Pop',
  'Latin Pop': 'Pop',
  'Indie Pop': 'Pop',
  'Art Pop': 'Pop',
  'Pop Rock': 'Pop',
  'Pop Punk': 'Pop',
  'Pop Rap': 'Pop',
  'Arabian Pop': 'Pop',
  'Arabic Pop': 'Pop',
  'Khaleeji Pop': 'Pop',
  'Gulf Pop': 'Pop',
  'Turkish Pop': 'Pop',
  'Persian Pop': 'Pop',
  'Power Pop': 'Pop',
  'Jangle Pop': 'Pop',
  'Noise Pop': 'Pop',
  'Indonesian Pop': 'Pop',
  'Malaysian Pop': 'Pop',
  'Polynesian Pop': 'Pop',
  'Mediterranean Pop': 'Pop',
  'Khmer Pop': 'Pop',
  'North Korean Pop': 'Pop',
  'Sri Lankan Pop': 'Pop',
  'OPM': 'Pop',
  'Technopop': 'Pop',
  'Bollywood': 'Pop',
  'Filmi': 'Pop',
  'Chanson': 'Pop',

  // ── Rock family ──
  'Punk': 'Rock',
  'Punk Rock': 'Rock',
  'Grunge': 'Rock',
  'Alternative Rock': 'Rock',
  'Alternative': 'Rock',
  'Indie Rock': 'Rock',
  'Indie': 'Rock',
  'Psychedelic Rock': 'Rock',
  'Psychedelic': 'Rock',
  'Post-Punk': 'Rock',
  'New Wave': 'Rock',
  'Heavy Metal': 'Rock',
  'Hard Rock': 'Rock',
  'Britpop': 'Rock',
  'Merseybeat': 'Rock',
  'Progressive Rock': 'Rock',
  'Classic Rock': 'Rock',
  'Heartland Rock': 'Rock',
  'Southern Rock': 'Rock',
  'Nu-Metal': 'Rock',
  'Metalcore': 'Rock',
  'Death Metal': 'Rock',
  'Black Metal': 'Rock',
  'Thrash Metal': 'Rock',
  'Extreme Metal': 'Rock',
  'Groove Metal': 'Rock',
  'Metal': 'Rock',
  'Noise Rock': 'Rock',
  'Art Rock': 'Rock',
  'Post-Rock': 'Rock',
  'Math Rock': 'Rock',
  'Emo': 'Rock',
  'Screamo': 'Rock',
  'Post-Hardcore': 'Rock',
  'Hardcore Punk': 'Rock',
  'Hardcore': 'Rock',
  'Anatolian Rock': 'Rock',
  'Rockabilly': 'Rock',
  'Rock & Roll': 'Rock',
  'Rock and Roll': 'Rock',
  'Folk Rock': 'Rock',
  'Folk Punk': 'Rock',
  'Country Rock': 'Rock',
  'Blues Rock': 'Rock',
  'Acid Rock': 'Rock',
  'Noise': 'Rock',
  'Experimental': 'Rock',
  'Shock Rock': 'Rock',
  'Pub Rock': 'Rock',
  'Raga Rock': 'Rock',
  'Desert Rock': 'Rock',
  'Cambodian Rock': 'Rock',
  'Malay Rock': 'Rock',
  'Japanese Rock': 'Rock',
  'Filipino Rock': 'Rock',
  'Aboriginal Rock': 'Rock',
  'Post-Soviet Rock': 'Rock',
  'Group Sounds': 'Rock',
  'Zamrock': 'Rock',
  'Rock en Español': 'Rock',
  'Punta Rock': 'Rock',
  'Jam Band': 'Rock',
  'Indie Dance': 'Rock',
  'Lo-Fi': 'Rock',
  'Sound Art': 'Rock',
  'Arabic Indie Rock': 'Rock',

  // ── Jazz family ──
  'Bebop': 'Jazz',
  'Swing': 'Jazz',
  'Free Jazz': 'Jazz',
  'Avant-Garde Jazz': 'Jazz',
  'Dixieland': 'Jazz',
  'Vocal Jazz': 'Jazz',
  'Cape Jazz': 'Jazz',
  'Ethio-Jazz': 'Jazz',
  'Afro-Cuban Jazz': 'Jazz',
  'Latin Jazz': 'Jazz',
  'Ragtime': 'Jazz',
  'Somali Jazz': 'Jazz',
  'Azerbaijani Jazz': 'Jazz',
  'Afro-Jazz': 'Jazz',
  'Jug Band': 'Jazz',
  'Lounge': 'Jazz',
  'Musical Theatre': 'Jazz',
  'Vaudeville': 'Jazz',

  // ── R&B / Soul / Funk family ──
  'Soul': 'R&B',
  'Funk': 'R&B',
  'Motown': 'R&B',
  'Disco': 'R&B',
  'Gospel': 'R&B',
  'Gospel Choir': 'R&B',
  'Go-Go': 'R&B',
  'Philadelphia Soul': 'R&B',
  'Southern Soul': 'R&B',
  'Minneapolis Sound': 'R&B',
  'Ska': 'R&B',
  'Ska Revival': 'R&B',
  '2 Tone': 'R&B',
  'Lovers Rock': 'R&B',
  'Rocksteady': 'R&B',
  'Afro-Funk': 'R&B',
  'Thai Funk': 'R&B',
  'Tribal Funk': 'R&B',

  // ── Hip Hop family ──
  'Rap': 'Hip Hop',
  'Trap': 'Hip Hop',
  'Drill': 'Hip Hop',
  'UK Drill': 'Hip Hop',
  'Grime': 'Hip Hop',
  'Southern Hip Hop': 'Hip Hop',
  'West Coast Hip Hop': 'Hip Hop',
  'G-Funk': 'Hip Hop',
  'Crunk': 'Hip Hop',
  'Chopped & Screwed': 'Hip Hop',
  'Conscious Rap': 'Hip Hop',
  'Rap Rock': 'Hip Hop',
  'Indie Hip Hop': 'Hip Hop',
  'Latin Trap': 'Hip Hop',
  'Hiplife': 'Hip Hop',
  'Hipco': 'Hip Hop',
  'Motswako': 'Hip Hop',
  'Bongo Flava': 'Hip Hop',
  'Baile Funk': 'Hip Hop',
  'Indian Hip Hop': 'Hip Hop',
  'Gully Rap': 'Hip Hop',
  'African Hip Hop': 'Hip Hop',
  'Japanese Hip Hop': 'Hip Hop',
  'Brazilian Hip Hop': 'Hip Hop',
  'K-Hip Hop': 'Hip Hop',
  'Cuban Hip Hop': 'Hip Hop',
  'Mahraganat': 'Hip Hop',
  'Arabic Indie': 'Hip Hop',
  'Ragga': 'Hip Hop',
  'Afroswing': 'Hip Hop',

  // ── Electronic family ──
  'Techno': 'Electronic',
  'House': 'Electronic',
  'EDM': 'Electronic',
  'Trance': 'Electronic',
  'Psytrance': 'Electronic',
  'Goa Trance': 'Electronic',
  'Drum and Bass': 'Electronic',
  'Jungle': 'Electronic',
  'Trip-Hop': 'Electronic',
  'Trip Hop': 'Electronic',
  'Acid House': 'Electronic',
  'Dubstep': 'Electronic',
  'Minimal Techno': 'Electronic',
  'French Touch': 'Electronic',
  'Balearic Beat': 'Electronic',
  'Hardstyle': 'Electronic',
  'EBM': 'Electronic',
  'New Beat': 'Electronic',
  'Madchester': 'Electronic',
  'Industrial': 'Electronic',
  'Krautrock': 'Electronic',
  'Kuduro': 'Electronic',
  'Amapiano': 'Electronic',
  'Dancehall': 'Electronic',
  'Dance': 'Electronic',
  'Dance Music': 'Electronic',
  'Rave': 'Electronic',
  'Baltimore Club': 'Electronic',
  'Sound System': 'Electronic',
  'DJ Style': 'Electronic',
  'Dub': 'Electronic',
  'Asian Underground': 'Electronic',
  'Kwaito': 'Electronic',

  // ── Classical family ──
  'Opera': 'Classical',
  'Baroque': 'Classical',
  'Romantic': 'Classical',
  'Impressionism': 'Classical',
  'Minimalism': 'Classical',
  'Sacred': 'Classical',
  'Sacred Music': 'Classical',
  'Choral': 'Classical',
  'Symphonic': 'Classical',
  'Indian Classical': 'Classical',
  'Hindustani Classical': 'Classical',
  'Carnatic': 'Classical',
  'Persian Classical': 'Classical',
  'Arabic Classical': 'Classical',
  'Ottoman Classical': 'Classical',
  'Gamelan': 'Classical',
  'Gagaku': 'Classical',
  'Mugham': 'Classical',
  'Shashmaqam': 'Classical',
  'Pansori': 'Classical',
  'Peking Opera': 'Classical',
  'Film Music': 'Classical',
  'Avant-Garde': 'Classical',
  'Ballet': 'Classical',
  'Chamber Music': 'Classical',
  'Gregorian Chant': 'Classical',
  'Chinese Classical': 'Classical',
  'Japanese Classical': 'Classical',
  'Javanese Classical': 'Classical',
  'Khmer Classical': 'Classical',
  'Burmese Classical': 'Classical',
  'Vietnamese Classical': 'Classical',
  'Thai Classical': 'Classical',
  'Korean Classical': 'Classical',
  'Afghan Classical': 'Classical',
  'Azerbaijani Classical': 'Classical',
  'Armenian Classical': 'Classical',
  'Tajik Classical': 'Classical',
  'Central Asian Classical': 'Classical',
  'Moorish Classical': 'Classical',
  'Andalusi Classical': 'Classical',
  'Malay Classical': 'Classical',
  'Revolutionary Opera': 'Classical',
  'Court Music': 'Classical',
  'Nha nhac': 'Classical',
  'Nanguan': 'Classical',
  'Yayue': 'Classical',
  'Jeongak': 'Classical',
  'Piphat': 'Classical',
  'Pinpeat': 'Classical',
  'Mahori': 'Classical',
  'Dastgah': 'Classical',
  'Makam': 'Classical',
  'Iraqi Maqam': 'Classical',
  'Maqam': 'Classical',
  'Odissi': 'Classical',
  'Neapolitan Song': 'Classical',
  'Confucian': 'Classical',
  'Classical Fusion': 'Classical',
  'Polyphony': 'Classical',
  'Georgian Polyphony': 'Classical',
  'Iso-Polyphony': 'Classical',
  'Pygmy Polyphony': 'Classical',

  // ── Folk / World family ──
  'Blues': 'Folk',
  'Country': 'Folk',
  'Country Blues': 'Folk',
  'Chicago Blues': 'Folk',
  'Piedmont Blues': 'Folk',
  'British Blues': 'Folk',
  'Desert Blues': 'Folk',
  'Tuareg Blues': 'Folk',
  'Bluegrass': 'Folk',
  'Reggae': 'Folk',
  'Roots Reggae': 'Folk',
  'Island Reggae': 'Folk',
  'Pacific Reggae': 'Folk',
  'Reggaeton': 'Folk',
  'Bossa Nova': 'Folk',
  'Samba': 'Folk',
  'Samba de Roda': 'Folk',
  'Samba-Reggae': 'Folk',
  'Tango': 'Folk',
  'Fado': 'Folk',
  'Flamenco': 'Folk',
  'Cumbia': 'Folk',
  'Salsa': 'Folk',
  'Merengue': 'Folk',
  'Bachata': 'Folk',
  'Afrobeats': 'Folk',
  'Afrobeat': 'Folk',
  'Highlife': 'Folk',
  'Mbalax': 'Folk',
  'World Music': 'Folk',
  'Raï': 'Folk',
  'Qawwali': 'Folk',
  'Rebetiko': 'Folk',
  'Gnawa': 'Folk',
  'Steelpan': 'Folk',
  'Celtic': 'Folk',
  'Traditional': 'Folk',
  'Appalachian': 'Folk',
  'Singer-Songwriter': 'Folk',
  'Roots': 'Folk',
  'Protest': 'Folk',
  'Protest Music': 'Folk',
  'Americana': 'Folk',
  'Acadian': 'Folk',
  'Old-Time': 'Folk',
  'Hawaiian': 'Folk',
  'Native American': 'Folk',
  'Indigenous': 'Folk',
  'Calypso': 'Folk',
  'Soca': 'Folk',
  'Ragga Soca': 'Folk',
  'Mento': 'Folk',
  'Kaiso': 'Folk',
  'Latin': 'Folk',
  'Son Cubano': 'Folk',
  'Son Montuno': 'Folk',
  'Mambo': 'Folk',
  'Bolero': 'Folk',
  'Cha-cha-chá': 'Folk',
  'Charanga': 'Folk',
  'Contradanza': 'Folk',
  'Danzón': 'Folk',
  'Mariachi': 'Folk',
  'Ranchera': 'Folk',
  'Norteño': 'Folk',
  'Regional Mexican': 'Folk',
  'Tropicália': 'Folk',
  'MPB': 'Folk',
  'Axé': 'Folk',
  'Maxixe': 'Folk',
  'Lundu': 'Folk',
  'Outlaw Country': 'Folk',
  'Rodeo Country': 'Folk',
  'Cowboy Music': 'Folk',
  'Western': 'Folk',
  'Fiddle': 'Folk',
  'Harp Music': 'Folk',
  'String Band': 'Folk',
  'Afro-Pop': 'Folk',
  'Afro-Peruvian': 'Folk',
  'Afro-Cuban': 'Folk',
  'Afro-Manding': 'Folk',
  'Afro-Portuguese': 'Folk',
  'Afro-Fusion': 'Folk',
  'Afro-Psych': 'Folk',
  'Soukous': 'Folk',
  'Congolese Rumba': 'Folk',
  'Rumba Congolaise': 'Folk',
  'Rumba': 'Folk',
  'Makossa': 'Folk',
  'Mbaqanga': 'Folk',
  'Township Jive': 'Folk',
  'Mbira': 'Folk',
  'Chimurenga': 'Folk',
  'Jùjú': 'Folk',
  'Palm Wine': 'Folk',
  'Griot': 'Folk',
  'Griot Tradition': 'Folk',
  'Kora Music': 'Folk',
  'West African': 'Folk',
  'Mandingue': 'Folk',
  'Salegy': 'Folk',
  'Morna': 'Folk',
  'Sega': 'Folk',
  'Seggae': 'Folk',
  'Gumbe': 'Folk',
  'Maringa': 'Folk',
  'Twarab': 'Folk',
  'Tarab': 'Folk',
  'Benga': 'Folk',
  'Kadongo Kamu': 'Folk',
  'Royal Drumming': 'Folk',
  'African Drumming': 'Folk',
  'Devotional': 'Folk',
  'Spiritual': 'Folk',
  'Sufi Music': 'Folk',
  'Baul': 'Folk',
  'Throat Singing': 'Folk',
  'Call and Response': 'Folk',
  'Ring Shout': 'Folk',
  'Ritual': 'Folk',
  'Mardi Gras Indian': 'Folk',
  'Brass Band': 'Folk',
  'Slack-Key Guitar': 'Folk',
  'Powwow': 'Folk',
  'Pasillo': 'Folk',
  'Guarania': 'Folk',
  'Chicha': 'Folk',
  'Festejo': 'Folk',
  'Landó': 'Folk',
  'Punta': 'Folk',
  'Dembow': 'Folk',
  'Kompa': 'Folk',
  'Rara': 'Folk',
  'Bouyon': 'Folk',
  'Dennery Segment': 'Folk',
  'Cadence-lypso': 'Folk',
  'Spouge': 'Folk',
  'Goombay': 'Folk',
  'Junkanoo': 'Folk',
  'Kaseko': 'Folk',
  'Kawina': 'Folk',
  'Candombe': 'Folk',
  'Baila': 'Folk',
  'Dangdut': 'Folk',
  'Luk Thung': 'Folk',
  'Lam': 'Folk',
  'Khene Music': 'Folk',
  'Ca Tru': 'Folk',
  'Xinyao': 'Folk',
  'Tabla': 'Folk',
  'Duduk': 'Folk',
  'Dutar': 'Folk',
  'Rubab': 'Folk',
  'Oud Music': 'Folk',
  'Dombra': 'Folk',
  'Gulingtangan': 'Folk',
  'Marimba': 'Folk',
  'Panpipe Ensemble': 'Folk',
  'Turbo-Folk': 'Folk',
  'Indie Folk': 'Folk',
  'Scandinavian Folk': 'Folk',
  'Greek Folk': 'Folk',
  'Turkish Folk': 'Folk',
  'Armenian Folk': 'Folk',
  'Kazakh Folk': 'Folk',
  'Kyrgyz Folk': 'Folk',
  'Turkmen Folk': 'Folk',
  'Bengali Folk': 'Folk',
  'Nepali Folk': 'Folk',
  'Bhutanese Folk': 'Folk',
  'Pashto Folk': 'Folk',
  'Afar Folk': 'Folk',
  'Omani Folk': 'Folk',
  'Lebanese Folk': 'Folk',
  'Andean Folk': 'Folk',
  'Vietnamese Folk': 'Folk',
  'Maldivian Folk': 'Folk',
  'Sudanese Folk': 'Folk',
  'Nauruan Folk': 'Folk',
  'Fijian Folk': 'Folk',
  'Fijian Choral': 'Folk',
  'Samoan Choral': 'Folk',
  'Tongan Choral': 'Folk',
  'Tuvaluan Choral': 'Folk',
  'Pacific Folk': 'Folk',
  'Pacific Island Music': 'Folk',
  'Haka': 'Folk',
  'Māori Music': 'Folk',
  'Fatele': 'Folk',
  'Lakalaka': 'Folk',
  'Sing-Sing': 'Folk',
  'Custom Music': 'Folk',
  'Kiribati Chant': 'Folk',
  'Marshallese Chant': 'Folk',
  'Palauan Chant': 'Folk',
  'Micronesian Chant': 'Folk',
  'Omengat Song': 'Folk',
  'Dinka Chant': 'Folk',
  'Bodu Beru': 'Folk',
  'Balélé': 'Folk',
  'Moutya': 'Folk',
  'Famo': 'Folk',
  'Malipenga': 'Folk',
  'Sibhaca': 'Folk',
  'Sesotho Traditional': 'Folk',
  'Swazi Traditional': 'Folk',
  'Guayla': 'Folk',
  'Tigrinya Music': 'Folk',
  'Somali Music': 'Folk',
  'Qaraami': 'Folk',
  'Haqiba': 'Folk',
  'Fado Timorense': 'Folk',
  "Fa'ataupati": 'Folk',
  'Te Bino': 'Folk',
  'Rigsar': 'Folk',
  'Newari Folk': 'Folk',
  'Mongolian Folk': 'Folk',
  'Akyns': 'Folk',
  'Bakhshi': 'Folk',
  'Stick Dance': 'Folk',
  'Warba': 'Folk',
  'Fihiri': 'Folk',
  'Liwa': 'Folk',
  'Khaliji': 'Folk',
  'Sawt': 'Folk',
  'Muwashah': 'Folk',
  "Ma'luf": 'Folk',
  'Malouf': 'Folk',
  'Chaabi': 'Folk',
  'Andalusian': 'Folk',
  'Arabesque': 'Folk',
  'Mizrahi': 'Folk',
  'Revival': 'Folk',
  'Roma Brass': 'Folk',
  'Festival': 'Folk',
  'Candomblé': 'Folk',
  'Vodou Drumming': 'Folk',
  'Vodun Music': 'Folk',
  'Bwiti Music': 'Folk',
  'Kumina': 'Folk',
  'Maroon Music': 'Folk',
  'Caribbean': 'Folk',
  'Antigua Benna': 'Folk',
  "Al-Ghina Al-San'ani": 'Folk',
  'Falak': 'Folk',
  'Shambo': 'Folk',
  'Mgodro': 'Folk',
  'Zouglou': 'Folk',
  'Coupé-Décalé': 'Folk',
  'Ghana': 'Folk',
  'Resistance Music': 'Folk',
  'Acoustic': 'Folk',
  'Cumbia Peruana': 'Folk',
  'Cumbia Sonidera': 'Folk',
  'Cumbia Villera': 'Folk',
  'Pachanga': 'Folk',
  'Latin Boogaloo': 'Folk',
  'Salsa Romántica': 'Folk',
  'Son Nica': 'Folk',
  'Timba': 'Folk',
  'Afoxé': 'Folk',
  'Chutney': 'Folk',
  'Reggae en Español': 'Folk',
  'Marrabenta': 'Folk',
  'Ússua': 'Folk',
  'Spanish-African Fusion': 'Folk',
  'Secular': 'Folk',
  'Thangyat': 'Folk',
  'Sai': 'Folk',
  'Nueva Canción': 'Folk',
  'Fihiri': 'Folk',
  'Socopé': 'Folk',
}

/**
 * Map a Globe event genre string to the closest Learn course name.
 * Returns null if no reasonable match is found.
 */
export function mapGenreToCourse(genre: string): LearnCourse | null {
  // Pass 1: exact match
  if (genre in GENRE_TO_COURSE) return GENRE_TO_COURSE[genre]

  // Pass 2: substring match (e.g., "Chicago Blues" contains "Blues")
  for (const [key, course] of Object.entries(GENRE_TO_COURSE)) {
    if (genre.includes(key) && key.length >= 3) return course
  }

  return null
}

/** URL-safe slug for a course name */
export function courseToSlug(course: LearnCourse): string {
  return course.toLowerCase().replace(/\s+/g, '-')
}
