/**
 * Maps Globe event genres to the 14 curriculum genres + Classical.
 * Two-pass lookup: exact match first, then substring match.
 *
 * Source of truth: Chord Progression Library style tags + genreIdMap.ts
 */

/** The 14 curriculum genres + non-curriculum categories */
export type CurriculumCourse =
  | 'Pop'
  | 'Rock'
  | 'Jazz'
  | 'Blues'
  | 'Folk'
  | 'Funk'
  | 'R&B'
  | 'Neo Soul'
  | 'Hip Hop'
  | 'Electronic'
  | 'Latin'
  | 'Reggae'
  | 'African'
  | 'Jam Band'
  | 'Classical'
  | 'Film Scoring'
  | 'Musical Theatre'
  | 'Jingles';

const GENRE_TO_CURRICULUM: Record<string, CurriculumCourse> = {
  // ── Direct matches (14 curriculum genres) ──
  Pop: 'Pop',
  Rock: 'Rock',
  Jazz: 'Jazz',
  Blues: 'Blues',
  Folk: 'Folk',
  Funk: 'Funk',
  'R&B': 'R&B',
  'Neo Soul': 'Neo Soul',
  'Hip Hop': 'Hip Hop',
  Electronic: 'Electronic',
  Latin: 'Latin',
  Reggae: 'Reggae',
  African: 'African',
  'Jam Band': 'Jam Band',
  Classical: 'Classical',

  // ── Pop family ──
  'K-Pop': 'Pop',
  'J-Pop': 'Pop',
  'City Pop': 'Pop',
  'C-Pop': 'Pop',
  Mandopop: 'Pop',
  'Synth-Pop': 'Pop',
  'Synth Pop': 'Pop',
  'Latin Pop': 'Pop',
  'Indie Pop': 'Pop',
  'Art Pop': 'Pop',
  'Pop Rock': 'Pop',
  'Pop Punk': 'Pop',
  'Pop Rap': 'Pop',
  'Arabian Pop': 'Pop',
  'Arabic Pop': 'Pop',
  'Khaleeji Pop': 'Pop',
  'Gulf Pop': 'Pop',
  'Turkish Pop': 'Pop',
  'Persian Pop': 'Pop',
  'Power Pop': 'Pop',
  'Jangle Pop': 'Pop',
  'Noise Pop': 'Pop',
  'Indonesian Pop': 'Pop',
  'Malaysian Pop': 'Pop',
  'Polynesian Pop': 'Pop',
  'Mediterranean Pop': 'Pop',
  'Khmer Pop': 'Pop',
  'North Korean Pop': 'Pop',
  'Sri Lankan Pop': 'Pop',
  OPM: 'Pop',
  Technopop: 'Pop',
  Bollywood: 'Pop',
  Filmi: 'Pop',
  Chanson: 'Pop',

  // ── Rock family ──
  Punk: 'Rock',
  'Punk Rock': 'Rock',
  Grunge: 'Rock',
  'Alternative Rock': 'Rock',
  Alternative: 'Rock',
  'Indie Rock': 'Rock',
  Indie: 'Rock',
  'Psychedelic Rock': 'Rock',
  Psychedelic: 'Rock',
  'Post-Punk': 'Rock',
  'New Wave': 'Rock',
  'Heavy Metal': 'Rock',
  'Hard Rock': 'Rock',
  Britpop: 'Rock',
  Merseybeat: 'Rock',
  'Progressive Rock': 'Rock',
  'Classic Rock': 'Rock',
  'Heartland Rock': 'Rock',
  'Southern Rock': 'Rock',
  'Nu-Metal': 'Rock',
  Metalcore: 'Rock',
  'Death Metal': 'Rock',
  'Black Metal': 'Rock',
  'Thrash Metal': 'Rock',
  'Extreme Metal': 'Rock',
  'Groove Metal': 'Rock',
  Metal: 'Rock',
  'Noise Rock': 'Rock',
  'Art Rock': 'Rock',
  'Post-Rock': 'Rock',
  'Math Rock': 'Rock',
  Emo: 'Rock',
  Screamo: 'Rock',
  'Post-Hardcore': 'Rock',
  'Hardcore Punk': 'Rock',
  Hardcore: 'Rock',
  'Anatolian Rock': 'Rock',
  Rockabilly: 'Rock',
  'Rock & Roll': 'Rock',
  'Rock and Roll': 'Rock',
  'Folk Rock': 'Rock',
  'Folk Punk': 'Rock',
  'Country Rock': 'Rock',
  'Blues Rock': 'Rock',
  'Acid Rock': 'Rock',
  Noise: 'Rock',
  Experimental: 'Rock',
  'Shock Rock': 'Rock',
  'Pub Rock': 'Rock',
  'Raga Rock': 'Rock',
  'Desert Rock': 'Rock',
  'Cambodian Rock': 'Rock',
  'Malay Rock': 'Rock',
  'Japanese Rock': 'Rock',
  'Filipino Rock': 'Rock',
  'Aboriginal Rock': 'Rock',
  'Post-Soviet Rock': 'Rock',
  'Group Sounds': 'Rock',
  Zamrock: 'Rock',
  'Rock en Español': 'Rock',
  'Punta Rock': 'Rock',
  'Indie Dance': 'Rock',
  'Lo-Fi': 'Rock',
  'Sound Art': 'Rock',
  'Arabic Indie Rock': 'Rock',

  // ── Jazz family ──
  Bebop: 'Jazz',
  Swing: 'Jazz',
  'Free Jazz': 'Jazz',
  'Avant-Garde Jazz': 'Jazz',
  Dixieland: 'Jazz',
  'Vocal Jazz': 'Jazz',
  'Cape Jazz': 'Jazz',
  'Ethio-Jazz': 'Jazz',
  'Afro-Cuban Jazz': 'Jazz',
  'Latin Jazz': 'Jazz',
  Ragtime: 'Jazz',
  'Somali Jazz': 'Jazz',
  'Azerbaijani Jazz': 'Jazz',
  'Afro-Jazz': 'Jazz',
  'Jug Band': 'Jazz',
  Lounge: 'Jazz',
  'Musical Theatre': 'Musical Theatre',
  Vaudeville: 'Jazz',

  // ── Blues family ──
  'Country Blues': 'Blues',
  'Chicago Blues': 'Blues',
  'Piedmont Blues': 'Blues',
  'British Blues': 'Blues',
  'Desert Blues': 'Blues',
  'Tuareg Blues': 'Blues',

  // ── Folk family ──
  Country: 'Folk',
  Bluegrass: 'Folk',
  Celtic: 'Folk',
  Traditional: 'Folk',
  Appalachian: 'Folk',
  'Singer-Songwriter': 'Folk',
  Roots: 'Folk',
  Protest: 'Folk',
  'Protest Music': 'Folk',
  Americana: 'Folk',
  Acadian: 'Folk',
  'Old-Time': 'Folk',
  Hawaiian: 'Folk',
  'Native American': 'Folk',
  Indigenous: 'Folk',
  'Outlaw Country': 'Folk',
  'Rodeo Country': 'Folk',
  'Cowboy Music': 'Folk',
  Western: 'Folk',
  Fiddle: 'Folk',
  'Harp Music': 'Folk',
  'String Band': 'Folk',
  'Turbo-Folk': 'Folk',
  'Indie Folk': 'Folk',
  'Scandinavian Folk': 'Folk',
  'Greek Folk': 'Folk',
  'Turkish Folk': 'Folk',
  'Armenian Folk': 'Folk',
  'Kazakh Folk': 'Folk',
  'Kyrgyz Folk': 'Folk',
  'Turkmen Folk': 'Folk',
  'Bengali Folk': 'Folk',
  'Nepali Folk': 'Folk',
  'Bhutanese Folk': 'Folk',
  'Pashto Folk': 'Folk',
  'Afar Folk': 'Folk',
  'Omani Folk': 'Folk',
  'Lebanese Folk': 'Folk',
  'Andean Folk': 'Folk',
  'Vietnamese Folk': 'Folk',
  'Maldivian Folk': 'Folk',
  'Sudanese Folk': 'Folk',
  'Nauruan Folk': 'Folk',
  'Fijian Folk': 'Folk',
  'Pacific Folk': 'Folk',
  'Pacific Island Music': 'Folk',
  'Newari Folk': 'Folk',
  'Mongolian Folk': 'Folk',
  'Slack-Key Guitar': 'Folk',
  Powwow: 'Folk',
  Acoustic: 'Folk',
  'World Music': 'Folk',
  Fado: 'Folk',
  Flamenco: 'Folk',
  Rebetiko: 'Folk',

  // ── Funk family ──
  'Go-Go': 'Funk',
  'Minneapolis Sound': 'Funk',
  'Afro-Funk': 'Funk',
  'Thai Funk': 'Funk',
  'Tribal Funk': 'Funk',

  // ── R&B / Soul family ──
  Soul: 'R&B',
  Motown: 'R&B',
  Disco: 'R&B',
  'Philadelphia Soul': 'R&B',
  'Southern Soul': 'R&B',

  // ── Neo Soul family ──
  // (Neo Soul is a direct match above)

  // ── Gospel (sub-genre crossover: R&B primary, also Jazz + Neo Soul) ──
  Gospel: 'R&B',
  'Gospel Choir': 'R&B',

  // ── Hip Hop family ──
  Rap: 'Hip Hop',
  Trap: 'Hip Hop',
  Drill: 'Hip Hop',
  'UK Drill': 'Hip Hop',
  Grime: 'Hip Hop',
  'Southern Hip Hop': 'Hip Hop',
  'West Coast Hip Hop': 'Hip Hop',
  'G-Funk': 'Hip Hop',
  Crunk: 'Hip Hop',
  'Chopped & Screwed': 'Hip Hop',
  'Conscious Rap': 'Hip Hop',
  'Rap Rock': 'Hip Hop',
  'Indie Hip Hop': 'Hip Hop',
  'Latin Trap': 'Hip Hop',
  Hiplife: 'Hip Hop',
  Hipco: 'Hip Hop',
  Motswako: 'Hip Hop',
  'Bongo Flava': 'Hip Hop',
  'Baile Funk': 'Hip Hop',
  'Indian Hip Hop': 'Hip Hop',
  'Gully Rap': 'Hip Hop',
  'African Hip Hop': 'Hip Hop',
  'Japanese Hip Hop': 'Hip Hop',
  'Brazilian Hip Hop': 'Hip Hop',
  'K-Hip Hop': 'Hip Hop',
  'Cuban Hip Hop': 'Hip Hop',
  Mahraganat: 'Hip Hop',
  'Arabic Indie': 'Hip Hop',
  Ragga: 'Hip Hop',
  Afroswing: 'Hip Hop',

  // ── Electronic family ──
  Techno: 'Electronic',
  House: 'Electronic',
  EDM: 'Electronic',
  Trance: 'Electronic',
  Psytrance: 'Electronic',
  'Goa Trance': 'Electronic',
  'Drum and Bass': 'Electronic',
  Jungle: 'Electronic',
  'Trip-Hop': 'Electronic',
  'Trip Hop': 'Electronic',
  'Acid House': 'Electronic',
  Dubstep: 'Electronic',
  'Minimal Techno': 'Electronic',
  'French Touch': 'Electronic',
  'Balearic Beat': 'Electronic',
  Hardstyle: 'Electronic',
  EBM: 'Electronic',
  'New Beat': 'Electronic',
  Madchester: 'Electronic',
  Industrial: 'Electronic',
  Krautrock: 'Electronic',
  Kuduro: 'Electronic',
  Amapiano: 'Electronic',
  Dance: 'Electronic',
  'Dance Music': 'Electronic',
  Rave: 'Electronic',
  'Baltimore Club': 'Electronic',
  'Sound System': 'Electronic',
  'DJ Style': 'Electronic',
  'Asian Underground': 'Electronic',
  Kwaito: 'Electronic',

  // ── Latin family ──
  Salsa: 'Latin',
  Cumbia: 'Latin',
  Merengue: 'Latin',
  Bachata: 'Latin',
  Reggaeton: 'Latin',
  'Bossa Nova': 'Latin',
  Samba: 'Latin',
  'Samba de Roda': 'Latin',
  'Samba-Reggae': 'Latin',
  Tango: 'Latin',
  'Son Cubano': 'Latin',
  'Son Montuno': 'Latin',
  Mambo: 'Latin',
  Bolero: 'Latin',
  'Cha-cha-chá': 'Latin',
  Charanga: 'Latin',
  Contradanza: 'Latin',
  Danzón: 'Latin',
  Mariachi: 'Latin',
  Ranchera: 'Latin',
  Norteño: 'Latin',
  'Regional Mexican': 'Latin',
  Tropicália: 'Latin',
  MPB: 'Latin',
  Axé: 'Latin',
  Maxixe: 'Latin',
  Lundu: 'Latin',
  Pasillo: 'Latin',
  Guarania: 'Latin',
  Chicha: 'Latin',
  Festejo: 'Latin',
  Landó: 'Latin',
  Punta: 'Latin',
  Dembow: 'Latin',
  'Cumbia Peruana': 'Latin',
  'Cumbia Sonidera': 'Latin',
  'Cumbia Villera': 'Latin',
  Pachanga: 'Latin',
  'Latin Boogaloo': 'Latin',
  'Salsa Romántica': 'Latin',
  'Son Nica': 'Latin',
  Timba: 'Latin',
  'Nueva Canción': 'Latin',
  'Afro-Cuban': 'Latin',
  'Afro-Peruvian': 'Latin',

  // ── Reggae family ──
  Ska: 'Reggae',
  'Ska Revival': 'Reggae',
  '2 Tone': 'Reggae',
  Dancehall: 'Reggae',
  Dub: 'Reggae',
  Rocksteady: 'Reggae',
  'Lovers Rock': 'Reggae',
  'Roots Reggae': 'Reggae',
  'Island Reggae': 'Reggae',
  'Pacific Reggae': 'Reggae',
  'Reggae en Español': 'Reggae',
  Calypso: 'Reggae',
  Soca: 'Reggae',
  'Ragga Soca': 'Reggae',
  Mento: 'Reggae',
  Kaiso: 'Reggae',
  Steelpan: 'Reggae',
  Kompa: 'Reggae',
  Rara: 'Reggae',
  Bouyon: 'Reggae',
  'Dennery Segment': 'Reggae',
  'Cadence-lypso': 'Reggae',
  Spouge: 'Reggae',
  Goombay: 'Reggae',
  Junkanoo: 'Reggae',
  Kaseko: 'Reggae',
  Kawina: 'Reggae',
  Chutney: 'Reggae',
  Caribbean: 'Reggae',
  'Antigua Benna': 'Reggae',
  Kumina: 'Reggae',
  'Maroon Music': 'Reggae',
  Seggae: 'Reggae',

  // ── African family ──
  Afrobeats: 'African',
  Afrobeat: 'African',
  Highlife: 'African',
  Mbalax: 'African',
  Soukous: 'African',
  'Congolese Rumba': 'African',
  'Rumba Congolaise': 'African',
  Rumba: 'African',
  Makossa: 'African',
  Mbaqanga: 'African',
  'Township Jive': 'African',
  Mbira: 'African',
  Chimurenga: 'African',
  Jùjú: 'African',
  'Palm Wine': 'African',
  Griot: 'African',
  'Griot Tradition': 'African',
  'Kora Music': 'African',
  'West African': 'African',
  Mandingue: 'African',
  Salegy: 'African',
  Morna: 'African',
  Sega: 'African',
  Gumbe: 'African',
  Maringa: 'African',
  Twarab: 'African',
  Tarab: 'African',
  Benga: 'African',
  'Kadongo Kamu': 'African',
  'Royal Drumming': 'African',
  'African Drumming': 'African',
  'Afro-Pop': 'African',
  'Afro-Manding': 'African',
  'Afro-Portuguese': 'African',
  'Afro-Fusion': 'African',
  'Afro-Psych': 'African',
  Ghana: 'African',
  Zouglou: 'African',
  'Coupé-Décalé': 'African',
  Marrabenta: 'African',
  Ússua: 'African',
  'Spanish-African Fusion': 'African',
  Socopé: 'African',

  // ── Jam Band family ──
  // (Jam Band is a direct match above)

  // ── Classical family (non-curriculum) ──
  Opera: 'Classical',
  Baroque: 'Classical',
  Romantic: 'Classical',
  Impressionism: 'Classical',
  Minimalism: 'Classical',
  Sacred: 'Classical',
  'Sacred Music': 'Classical',
  Choral: 'Classical',
  Symphonic: 'Classical',
  'Indian Classical': 'Classical',
  'Hindustani Classical': 'Classical',
  Carnatic: 'Classical',
  'Persian Classical': 'Classical',
  'Arabic Classical': 'Classical',
  'Ottoman Classical': 'Classical',
  Gamelan: 'Classical',
  Gagaku: 'Classical',
  Mugham: 'Classical',
  Shashmaqam: 'Classical',
  Pansori: 'Classical',
  'Peking Opera': 'Classical',
  'Film Music': 'Film Scoring',
  'Avant-Garde': 'Classical',
  Ballet: 'Classical',
  'Chamber Music': 'Classical',
  'Gregorian Chant': 'Classical',
  'Chinese Classical': 'Classical',
  'Japanese Classical': 'Classical',
  'Javanese Classical': 'Classical',
  'Khmer Classical': 'Classical',
  'Burmese Classical': 'Classical',
  'Vietnamese Classical': 'Classical',
  'Thai Classical': 'Classical',
  'Korean Classical': 'Classical',
  'Afghan Classical': 'Classical',
  'Azerbaijani Classical': 'Classical',
  'Armenian Classical': 'Classical',
  'Tajik Classical': 'Classical',
  'Central Asian Classical': 'Classical',
  'Moorish Classical': 'Classical',
  'Andalusi Classical': 'Classical',
  'Malay Classical': 'Classical',
  'Revolutionary Opera': 'Classical',
  'Court Music': 'Classical',
  'Nha nhac': 'Classical',
  Nanguan: 'Classical',
  Yayue: 'Classical',
  Jeongak: 'Classical',
  Piphat: 'Classical',
  Pinpeat: 'Classical',
  Mahori: 'Classical',
  Dastgah: 'Classical',
  Makam: 'Classical',
  'Iraqi Maqam': 'Classical',
  Maqam: 'Classical',
  Odissi: 'Classical',
  'Neapolitan Song': 'Classical',
  Confucian: 'Classical',
  'Classical Fusion': 'Classical',
  Polyphony: 'Classical',
  'Georgian Polyphony': 'Classical',
  'Iso-Polyphony': 'Classical',
  'Pygmy Polyphony': 'Classical',

  // ── Film Scoring family (non-curriculum) ──
  'Film Scoring': 'Film Scoring',
  'Film Score': 'Film Scoring',
  Soundtrack: 'Film Scoring',

  // ── Musical Theatre family (non-curriculum) ──
  'Musical Theater': 'Musical Theatre',
  Broadway: 'Musical Theatre',
  Operetta: 'Musical Theatre',
  'Rock Opera': 'Musical Theatre',

  // ── Jingles / Sonic Branding (non-curriculum) ──
  Jingles: 'Jingles',
  Jingle: 'Jingles',
  'Sonic Branding': 'Jingles',

  // ── Video Game Music (tagged by authentic style, no dedicated mapping) ──
  'Video Game Music': 'Electronic',

  // ── World / Traditional (mapped to Folk as closest curriculum match) ──
  Raï: 'Folk',
  Qawwali: 'Folk',
  Gnawa: 'Folk',
  Devotional: 'Folk',
  Spiritual: 'Folk',
  'Sufi Music': 'Folk',
  Baul: 'Folk',
  'Throat Singing': 'Folk',
  'Call and Response': 'Folk',
  'Ring Shout': 'Folk',
  Ritual: 'Folk',
  'Mardi Gras Indian': 'Folk',
  'Brass Band': 'Folk',
  Baila: 'Folk',
  Dangdut: 'Folk',
  'Luk Thung': 'Folk',
  Lam: 'Folk',
  'Khene Music': 'Folk',
  'Ca Tru': 'Folk',
  Xinyao: 'Folk',
  Tabla: 'Folk',
  Duduk: 'Folk',
  Dutar: 'Folk',
  Rubab: 'Folk',
  'Oud Music': 'Folk',
  Dombra: 'Folk',
  Gulingtangan: 'Folk',
  Marimba: 'Folk',
  'Panpipe Ensemble': 'Folk',
  Candombe: 'Folk',
  Afoxé: 'Folk',
  Candomblé: 'Folk',
  'Vodou Drumming': 'Folk',
  'Vodun Music': 'Folk',
  'Bwiti Music': 'Folk',
  'Fijian Choral': 'Folk',
  'Samoan Choral': 'Folk',
  'Tongan Choral': 'Folk',
  'Tuvaluan Choral': 'Folk',
  Haka: 'Folk',
  'Māori Music': 'Folk',
  Fatele: 'Folk',
  Lakalaka: 'Folk',
  'Sing-Sing': 'Folk',
  'Custom Music': 'Folk',
  'Kiribati Chant': 'Folk',
  'Marshallese Chant': 'Folk',
  'Palauan Chant': 'Folk',
  'Micronesian Chant': 'Folk',
  'Omengat Song': 'Folk',
  'Dinka Chant': 'Folk',
  'Bodu Beru': 'Folk',
  Balélé: 'Folk',
  Moutya: 'Folk',
  Famo: 'Folk',
  Malipenga: 'Folk',
  Sibhaca: 'Folk',
  'Sesotho Traditional': 'Folk',
  'Swazi Traditional': 'Folk',
  Guayla: 'Folk',
  'Tigrinya Music': 'Folk',
  'Somali Music': 'Folk',
  Qaraami: 'Folk',
  Haqiba: 'Folk',
  'Fado Timorense': 'Folk',
  "Fa'ataupati": 'Folk',
  'Te Bino': 'Folk',
  Rigsar: 'Folk',
  Akyns: 'Folk',
  Bakhshi: 'Folk',
  'Stick Dance': 'Folk',
  Warba: 'Folk',
  Fihiri: 'Folk',
  Liwa: 'Folk',
  Khaliji: 'Folk',
  Sawt: 'Folk',
  Muwashah: 'Folk',
  "Ma'luf": 'Folk',
  Malouf: 'Folk',
  Chaabi: 'Folk',
  Andalusian: 'Folk',
  Arabesque: 'Folk',
  Mizrahi: 'Folk',
  Revival: 'Folk',
  'Roma Brass': 'Folk',
  Festival: 'Folk',
  "Al-Ghina Al-San'ani": 'Folk',
  Falak: 'Folk',
  Shambo: 'Folk',
  Mgodro: 'Folk',
  'Resistance Music': 'Folk',
  Secular: 'Folk',
  Thangyat: 'Folk',
  Sai: 'Folk',
};

/**
 * Map a Globe event genre string to the closest curriculum genre.
 * Returns null if no reasonable match is found.
 */
export function mapGenreToCourse(genre: string): CurriculumCourse | null {
  // Pass 1: exact match
  if (genre in GENRE_TO_CURRICULUM) return GENRE_TO_CURRICULUM[genre];

  // Pass 2: substring match (e.g., "Chicago Blues" contains "Blues")
  for (const [key, course] of Object.entries(GENRE_TO_CURRICULUM)) {
    if (genre.includes(key) && key.length >= 3) return course;
  }

  return null;
}

/** URL-safe slug for a curriculum genre */
export function courseToSlug(course: CurriculumCourse): string {
  return course.toLowerCase().replace(/\s+/g, '-');
}

// Re-export for backward compatibility
export type LearnCourse = CurriculumCourse;
