import {
  CHORD_RHYTHMS,
  GENRE_SWING,
  generateChordMidi,
  generateDrumMidi,
  getFirstChords,
  InstrumentChannel,
  StrumMode,
  VelocityTilt,
  type GenreName,
  type MidiNoteEvent,
} from '@prism/engine';
import { groupChordsByColor } from '@/daw/components/Prism/ColorSpectrum';
import { DEMO_PROGRESSION, demoChord, nextOptions } from '../../../music';
import type { TourDrum } from '../sceneTypes';

/**
 * The Micro Studio's music (pure — unit tested in
 * `__tests__/studioModel.test.ts`): Prism options and color groups for a
 * sequence, the demo's deterministic picks, and the clip Create writes —
 * generated by the app's real engine (`generateChordMidi` /
 * `generateDrumMidi`), then flattened into events for the scene's transport.
 */

export type TrackId = 'chords' | 'drums';
export type StyleName = 'Pop' | 'Rock' | 'Funk' | 'Hip Hop';

export const BPM = 120;
/** Ticks per 4/4 bar (480 PPQ). */
export const BAR = 1920;
export const BEAT = 480;
/** The 4-bar clip Create writes (one loop of the transport). */
export const CLIP_TICKS = BAR * 4;
/** 480 PPQ at 120 BPM: 960 ticks per second. */
export const TICKS_PER_MS = (BEAT * BPM) / 60_000;
/** Chords in the sequence (the real builder keeps going; the demo stops). */
export const MAX_CHORDS = 4;

/**
 * Chord rhythm per STYLE pill. Each pill's drum rhythm (`drums`, else its chord
 * rhythm) has the pill's genre in `GENRE_MAP`, so `generateDrumMidi` picks the
 * groove the real orchestrator would for that genre. Pop, the default, holds
 * each chord for a whole note but keeps the Pop groove (whole notes alone would
 * map to Ballad).
 */
export const STYLES: Record<
  StyleName,
  { rhythm: string; drums?: string; genre: GenreName }
> = {
  Pop: { rhythm: 'Whole Notes', drums: 'Quarters', genre: 'Pop' },
  Rock: { rhythm: '3-3-2 Eighths', genre: 'Rock' },
  Funk: { rhythm: 'Funk 1', genre: 'Funk' },
  'Hip Hop': { rhythm: 'Staccato Eighths', genre: 'Hip Hop' },
};
export const STYLE_NAMES = Object.keys(STYLES) as StyleName[];

/** A major key's root for a pitch class, between F♯3 and F4 (C → 60). */
export const keyRootFor = (pc: number) => 60 + (pc <= 5 ? pc : pc - 12);

/**
 * Prism's options for the next chord: nothing until a key is set, the graph's
 * first chords for an empty sequence, then the progression graph. A dead end
 * (or a full sequence) is `[]` — the real "No more options available".
 */
export const optionsFor = (s: {
  keyPc: number | null;
  seq: readonly string[];
}): string[] => {
  if (s.keyPc === null || s.seq.length >= MAX_CHORDS) return [];
  if (s.seq.length === 0)
    return getFirstChords().filter((t) => !t.includes('/'));
  return nextOptions([...s.seq]);
};

/** Options grouped by spectrum color (`KEY_COLORS` index → tokens). */
export const colorGroups = (options: readonly string[], keyRoot: number) =>
  groupChordsByColor(options, keyRoot, 'ionian');

/**
 * Which chord a click on a color adds. The real spectrum picks at random;
 * the demo prefers the tour progression's next chord when it is in the
 * clicked color, and otherwise rotates through the color's chords.
 */
export const pickFromColor = (
  group: readonly string[],
  seq: readonly string[],
  picks: number,
): string => {
  const onPath = seq.every((t, i) => DEMO_PROGRESSION[i] === t);
  const next = DEMO_PROGRESSION[seq.length];
  if (onPath && next !== undefined && group.includes(next)) return next;
  return group[picks % group.length];
};

/** The clip's four bars: 1 chord → AAAA, 2 → ABAB, 3 → ABCA, 4 → ABCD. */
export const barTokens = (clip: readonly string[]): string[] => {
  if (clip.length === 0) return [];
  if (clip.length === 3) return [...clip, clip[0]];
  return [0, 1, 2, 3].map((i) => clip[i % clip.length]);
};

export interface ChordRegion {
  startTick: number;
  endTick: number;
  token: string;
  /** Chord-ruler label, "C maj". */
  label: string;
  color: string;
  /** The voiced notes the region starts with. */
  midis: number[];
}

export type TransportEvent =
  | {
      tick: number;
      track: 'chords';
      midis: number[];
      seconds: number;
      velocity: number;
    }
  | { tick: number; track: 'drums'; drum: TourDrum; velocity: number };

export interface StudioSong {
  /** Token per bar (empty without a clip). */
  bars: string[];
  /** The chord clip's notes (empty without a clip). */
  chordNotes: MidiNoteEvent[];
  /** The drum groove (always there — the DRUMS clip exists from the start). */
  drumNotes: MidiNoteEvent[];
  regions: ChordRegion[];
  /** Both tracks' hits for the transport, sorted by tick. */
  events: TransportEvent[];
}

const DRUM_BY_NOTE: Record<number, TourDrum> = {
  36: 'kick',
  45: 'kick',
  47: 'kick',
  50: 'kick',
  37: 'snare',
  38: 'snare',
  39: 'snare',
  42: 'hat',
  44: 'hat',
  46: 'hat',
  49: 'hat',
  51: 'hat',
};

const CHORD_VELOCITY = 0.55;
/** Chords ring for 90% of their written length. */
const CHORD_GATE = 0.9;

const chordRegions = (
  bars: readonly string[],
  keyRoot: number,
  notes: readonly MidiNoteEvent[],
): ChordRegion[] => {
  const regions: ChordRegion[] = [];
  bars.forEach((token, i) => {
    const startTick = i * BAR;
    const prev = regions[regions.length - 1];
    if (prev && prev.token === token) {
      prev.endTick = startTick + BAR;
      return;
    }
    const inBar = notes.filter(
      (n) => n.startTick >= startTick && n.startTick < startTick + BAR,
    );
    const first = Math.min(...inBar.map((n) => n.startTick));
    const chord = demoChord(token, keyRoot);
    regions.push({
      startTick,
      endTick: startTick + BAR,
      token,
      label: chord.label,
      color: chord.color,
      midis: inBar
        .filter((n) => n.startTick === first)
        .map((n) => n.note)
        .sort((a, b) => a - b),
    });
  });
  return regions;
};

const chordEvents = (notes: readonly MidiNoteEvent[]): TransportEvent[] => {
  const byTick = new Map<number, MidiNoteEvent[]>();
  for (const n of notes) {
    const at = byTick.get(n.startTick);
    if (at) at.push(n);
    else byTick.set(n.startTick, [n]);
  }
  return [...byTick].map(([tick, hit]) => ({
    tick,
    track: 'chords',
    midis: hit.map((n) => n.note).sort((a, b) => a - b),
    seconds:
      (Math.max(...hit.map((n) => n.durationTicks)) / (TICKS_PER_MS * 1000)) *
      CHORD_GATE,
    velocity: CHORD_VELOCITY,
  }));
};

const drumEvents = (notes: readonly MidiNoteEvent[]): TransportEvent[] =>
  notes.flatMap((n): TransportEvent[] => {
    const drum = DRUM_BY_NOTE[n.note];
    return drum
      ? [
          {
            tick: n.startTick,
            track: 'drums',
            drum,
            velocity: (n.velocity / 127) * 0.8,
          },
        ]
      : [];
  });

/** What Create writes for a sequence, in a key and STYLE. */
export const buildSong = ({
  clip,
  keyRoot,
  style,
}: {
  clip: readonly string[] | null;
  keyRoot: number;
  style: StyleName;
}): StudioSong => {
  const { rhythm, drums = rhythm, genre } = STYLES[style];
  const swing = GENRE_SWING[genre];
  const bars = barTokens(clip ?? []);
  const chordNotes =
    bars.length === 0
      ? []
      : generateChordMidi({
          chordSeq: bars.map((t) => demoChord(t, keyRoot).midis),
          stringSeq: bars,
          rhythmPattern: CHORD_RHYTHMS[rhythm],
          swing,
          strum: StrumMode.Synchronized,
          strumAmount: 0,
          tilt: VelocityTilt.Balanced,
          tiltAmount: 0,
          channel: InstrumentChannel.Chords,
        }).events;
  const drumNotes = generateDrumMidi({
    rhythmName: drums,
    swing,
    bars: 4,
  }).events;
  return {
    bars,
    chordNotes,
    drumNotes,
    regions: chordRegions(bars, keyRoot, chordNotes),
    events: [...chordEvents(chordNotes), ...drumEvents(drumNotes)].sort(
      (a, b) => a.tick - b.tick,
    ),
  };
};

/**
 * Events whose absolute tick (`loop × CLIP_TICKS + tick`) falls in
 * [fromAbs, toAbs), for a transport that loops the clip — the window may
 * cross the loop point.
 */
export const eventsInWindow = <E extends { tick: number }>(
  events: readonly E[],
  fromAbs: number,
  toAbs: number,
): { event: E; abs: number }[] => {
  const out: { event: E; abs: number }[] = [];
  if (toAbs <= fromAbs) return out;
  const firstLoop = Math.floor(fromAbs / CLIP_TICKS);
  const lastLoop = Math.floor((toAbs - 1) / CLIP_TICKS);
  for (let loop = firstLoop; loop <= lastLoop; loop++) {
    for (const event of events) {
      const abs = loop * CLIP_TICKS + event.tick;
      if (abs >= fromAbs && abs < toAbs) out.push({ event, abs });
    }
  }
  return out;
};

/** Bar:beat:sixteenth, 1-based (`TransportBar.tsx` `formatPosition`, 4/4). */
export const formatPosition = (ticks: number): string => {
  const bar = Math.floor(ticks / BAR) + 1;
  const beat = (Math.floor((ticks % BAR) / BEAT) % 4) + 1;
  const sixteenth = Math.floor((ticks % BEAT) / 120) + 1;
  return `${bar}:${beat}:${sixteenth}`;
};

/** Piano-roll pitch range: 2 below the lowest note, at least 22 rows. */
export const rollRange = (
  notes: readonly { note: number }[],
  rows = 22,
): { lo: number; hi: number } => {
  if (notes.length === 0) return { lo: 58, hi: 58 + rows - 1 };
  const pitches = notes.map((n) => n.note);
  const lo = Math.min(...pitches) - 2;
  return { lo, hi: Math.max(lo + rows - 1, Math.max(...pitches) + 2) };
};

/** The chord-ruler region under a tick (within the clip). */
export const regionAt = (
  regions: readonly ChordRegion[],
  tick: number,
): ChordRegion | undefined =>
  regions.find((r) => tick >= r.startTick && tick < r.endTick);
